### ISSUE TITLE
SDL2 transparency of fill and primatives

### ISSUE THREAD

**Issue by mcpalmer1980** [pygame/pygame#1165] opened 2019-07-15 14:04 UTC
- [ ] step 1) make a unit test for: Calls to surface.fill((0,0,0,0)) and pygame.draw.xxx(surf, (0,0,0,0), ...) do not erase the area of a surface like it used to, but fills with black instead. (good first issue) The surface tests go in tests/surface.py and the draw one should go in tests/draw_test.py
- [ ] step 2) fix the transparency issues in src_c/surface.c and src_c/draw.c

---

I recently installed pygame2-dev2 for both python2 and python3. All three of my games, totaling 25,321 lines, ran without errors on both versions. There were only a few small issues fixed within a couple hours of experimenting. I thought my results might be useful to the developers.

**Platform:**
	Linux Mint 18.3 on Acer-576G-5762
	Intel i5-8250U 1.6Ghz, 8gb RAM, nVidia GeForce mx150 disabled during tests
	pygame 2.0.0.dev2 (SDL 2.0.9, python 2.7.12) - ran without errors
	pygame 2.0.0.dev2 (SDL 2.0.9, python 3.5.2) - ran without errors

**Issue #1: Transparency**
The first thing I noticed when starting my games was terribly ugly menus. The corners of my rounded rects were black, menu button outlines were wrongly filled, and the area around some text was colored wrong too. This left me worrying about my pygame2 experience.

pygame2-dev2 doesn't blit transparency as expected. Calls to surface.fill((0,0,0,0)) and pygame.draw.xxx(surf, (0,0,0,0), ...) do not erase the area of a surface like it used to, but fills with black instead. My sprites use per-pixel transparency and blit as before, but my menus use graphic primitives and needed to be changed. 

Perhaps a surface flag might have fixed my problem, but I added a colorkey to the menu surface and changed it to surface alpha instead. This fixed my round_rects, buttons, and labels. My multi-line text control uses its own surface that blits onto the menu surface, which had to be altered before anti-aliasing looked right.

**Comment by illume** [comment] 2019-07-15 14:45
Thanks again for the report! I added some tasks at the top of your issue.

See these for some known outstanding graphical issues with pygame 2.
- https://github.com/pygame/pygame/issues/721
- https://github.com/pygame/pygame/issues/864

**Comment by robertpfeiffer** [comment] 2019-08-02 07:32
Somebody else reported this bug affecting production code in Discord. Is there a test case like this in the test suite already?

```python
fade_in=pygame.Surface((100,100), 32)
fade_in.fill((255,0,0,128))
assert (fade_in.get_at((1,1))==(255,0,0,128))
# currently (255, 0, 0, 255)
```

**Comment by robertpfeiffer** [comment] 2019-08-10 08:21
This bug report is somewhat misleading. There is no bug in surface.fill() or draw.c as far as I can tell. The problem is mostly with convert_alpha not setting SRCALPHA correctly. #1235 will close this.

**Closed** 2019-08-11 09:59 UTC
Labels: Surface, draw, good first issue
