### ISSUE TITLE
failed loading libmpg123-0.dll also after reinstall

### ISSUE THREAD

**Issue by raghav3148** [pygame/pygame#2647] opened 2021-07-21 17:27 UTC
pycham error : failed loading libmpg123-0.dll

**Comment by MightyJosip** [comment] 2021-07-22 11:24
Not enough information, closing it now

**Closed by MightyJosip** 2021-07-22 11:24 UTC

**Comment by jacqobi** [comment] 2021-11-02 15:47
Hi @MightyJosip,
I am able to reproduce the issue without using PyCharm as well, found the root cause, possible solution and interim workaround for @raghav3148 and other affected users until fix is released.

The full error message, that i believe is the same also when using PyCharm, is:
> pygame.error: Failed loading libmpg123-0.dll: The specified module could not be found.
### Cause
Related to [bpo-36085](https://bugs.python.org/issue36085) on how the DLL loading is handled by Python interpreter on Windows.
As noted in the [change logs](https://docs.python.org/3/whatsnew/changelog.html#id213) but better described in [Python's 3.8 What's New](https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew)

> DLL dependencies for extension modules and DLLs loaded with ctypes on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with add_dll_directory() are searched for load-time dependencies.
Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution.
**_If your application relies on these mechanisms, you should check for add_dll_directory() and if it exists, use it to add your DLLs directory while loading your library._**
Note that Windows 7 users will need to ensure that Windows Update KB2533623 has been installed (this is also verified by the installer). (Contributed by Steve Dower in bpo-36085.)

### Proposed Solution
Adding the dll directory path to the __init__.py of pygame using the [os.add_dll_directory()](https://docs.python.org/3/library/os.html#os.add_dll_directory) under the Windows specific clause as documented below should do the trick.
```
...
...
# Choose Windows display driver
if os.name == 'nt':
    #pypy does not find the dlls, so we add package folder to PATH.
    pygame_dir = os.path.split(__file__)[0]
    os.environ['PATH'] = os.environ['PATH'] + ';' + pygame_dir
    #Fix for the bpo-36085 change in Python3.8 on Windows
    os.add_dll_directory(pygame_dir)
...
...
```

### Workarounds
1. add the lines below to your code when using pygame.
```
import os
os.add_dll_directory(<full path to pygame directory>)
```
2. Copy the claimed to be missing file **libmpg123-0.dll** from the pygame directory (usually located at **\<python install dir\>\site-packages\pygame** or somewhere in the **%APPDATA%** of the user) to **C:\Windows\System32** or **C:\Windows\SysWOW64**
