### ISSUE TITLE
Mouse gets stuck on right side of the window in virtual mouse input mode

### ISSUE THREAD

**Issue by soup-dog** [pygame/pygame#2778] opened 2021-10-19 02:53 UTC
**Environment:**

- **Operating system** Windows 10
- **Python version** 3.9.2
- **SDL version** 2.0.16
- **PyGame version** 2.0.2

**Current behavior:**

Mouse cursor becomes visible and gets stuck (will not move further right) on the right side of the window when in virtual mouse input mode (using `pygame.mouse.set_visible(False); pygame.event.set_grab(True)`. Cursor can still move up and down on right side.
Moving to the left, top and bottom sides of the window works as expected.

Bug does not occur in PyGame 2.0.1.

**Screenshots**

Before moving cursor to right side. Cursor is not visible and events are working normally.
![Untitled](https://user-images.githubusercontent.com/37825157/137835289-aa8b75e9-642f-490d-ae4a-32d5d73f1b65.png)

Cursor becomes visible on right side of window and will not move any further. (Green outline added by Windows Steps Recorder and not relevant)
![image](https://user-images.githubusercontent.com/37825157/137835614-447261ea-f8b4-4a9f-83d5-3cf80c840651.png)

**Steps to reproduce:**

Run the test code below with PyGame 2.0.2. Move the mouse cursor to the right side of the window.

**Test code**

```
import pygame

pygame.init()

if __name__ == '__main__':
    surface = pygame.display.set_mode((100, 100))

    pygame.mouse.set_visible(False)
    pygame.event.set_grab(True)

    while True:
        pygame.event.get()
```

Replace `pygame.event.get()` with the following to observe that no rightwards mouse motion is observed by `event.rel` when the cursor is stuck on the right side:
```
        for event in pygame.event.get():
            if event.type == pygame.MOUSEMOTION:
                print(event.rel[0])
```

**Comment by ankith26** [comment] 2021-10-19 03:36
Whoops, miss-click on the milestone.
Anyways coming to this issue, I would guess it's an SDL 2.0.16 bug, because pygame 2.0.1 used SDL 2.0.14 on windows, and we did not change anything much display related in 2.0.2

**Comment by ankith26** [comment] 2021-10-19 04:53
Weirdly enough, I cannot reproduce this issue, testing from pygame 2.0.0 on SDL 2.0.16. The only difference being that I am running Windows 11 and python 3.10

**Comment by Starbuck5** [comment] 2021-10-19 06:52
I can reproduce this on pygame 2.0.2 on SDL 2.0.16, Python 3.9, Windows 10.

**Comment by ankith26** [comment] 2021-12-25 13:23
yeah, perhaps this can be reported to the SDL folk. Before that, anyone who could reproduce this issue on SDL 2.0.16, could you try again with pygame 2.1.1 (which has SDL 2.0.18) to see if that fixes this issue?

**Comment by rethanon** [comment] 2021-12-26 00:52
I've tried to reproduce this but I just can't. Even using the same setup it was reported on (Windows 10, pygame 2.0.2, SDL 2.0.16, python 3.9.2) I can't reproduce it. I also tried changing Windows scaling, as suggested by @Starbuck5, but that made no difference either. Might need @soup-dog to confirm if any of the version updates to python / pygame / SDL resolved the issue for them.

**Comment by ankith26** [comment] 2022-05-24 10:05
This issue does not trigger with the latest SDL version, using pygame 2.1.2 or higher should fix this (confirmed by starbuck on discord at some point, forgot to close this sooner) 
feel free to re-open if this issue reproduces in the future for anyone

**Closed by ankith26** 2022-05-24 10:05 UTC
Labels: bug, Windows, confirmed/reproducible
