### ISSUE TITLE
Segfault when creating a child class of pygame.mixer.Sound

### ISSUE THREAD

**Issue by novialriptide** [pygame/pygame#3419] opened 2022-08-21 04:13 UTC
Here's the code and output:

```python
import pygame
pygame.init()

class Amogus(pygame.mixer.Sound):
    def __init__(self):
        pass

a = Amogus()
a.get_volume()
```
```
PS C:\Users\novia\documents\github\pygame> python test.py
pygame 2.1.2 (SDL 2.0.18, Python 3.9.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x0000c344 (most recent call first):
  File "C:\Users\novia\documents\github\pygame\test.py", line 9 in <module>
```

**Comment by Starbuck5** [comment] 2022-08-21 04:39
Perhaps this is because the expected `__init__` sets internal class state that is referenced in `get_volume()`.

**Comment by PurityLake** [comment] 2022-10-09 22:53
Seems the issue in the C code is that `snd_get_volume` requests a chunk which returns NULL then calling `Mix_VolumeChunk` on that null chunk.

Should this return something like None? Or should we raise an error?

**Comment by novialriptide** [comment] 2022-10-10 20:30
> Seems the issue in the C code is that `snd_get_volume` requests a `Mix_Chunk` which returns NULL then calling `Mix_VolumeChunk` on that null chunk.
> 
> Should this return something like None? Or should we raise an error?
> 
> Mainly the issue here anyway is incorrectly not called `super().__init__(*args, **kwargs)` or whatever is the case for Sound.
> 
> Also, ya it shouldn't be subclassable it's tp_flags includes `Py_TPFLAGS_BASETYPE`

I'm on my phone right now so I can't really rest this, but if we do mimic the behavior when we do `pygame.mixer.Sound(None)`

**Comment by PurityLake** [comment] 2022-10-10 20:41
> > Seems the issue in the C code is that `snd_get_volume` requests a `Mix_Chunk` which returns NULL then calling `Mix_VolumeChunk` on that null chunk.
> > Should this return something like None? Or should we raise an error?
> > Mainly the issue here anyway is incorrectly not called `super().__init__(*args, **kwargs)` or whatever is the case for Sound.
> > Also, ya it shouldn't be subclassable it's tp_flags includes `Py_TPFLAGS_BASETYPE`
> 
> I'm on my phone right now so I can't really test this, but we should mimic the behavior when we do `pygame.mixer.Sound(None)`

Seems to throw an exception when called with None, and doesn't get past the creation.

**Comment by oddbookworm** [comment] 2022-10-11 02:12
Seems to be fixed in current dev versions of pygame, so issue resolved?

**Comment by novialriptide** [comment] 2022-10-11 02:13
> Seems to be fixed in current dev versions of pygame, so issue resolved?

Nope, pygame 2.1.3.dev7 is returning a negative `-1/128` instead.

**Comment by PurityLake** [comment] 2022-10-11 02:14
Yup, issue is resolved. Believe it may have been an SDL issue and not a Pygame issue. Although I noticed an issue with the implementation that -1 should be returned and not divide by 128

**Comment by oddbookworm** [comment] 2022-10-11 02:14
> > Seems to be fixed in current dev versions of pygame, so issue resolved?
> 
> Nope, pygame 2.1.3.dev7 is returning a negative instead (`-1/128`).

Wouldn't this be a separate issue since this issue is about the segfault?

**Comment by PurityLake** [comment] 2022-10-11 02:21
I feel this issue can be closed, I don't feel it was a Pygame issue in the end that has resolved itself.

**Comment by novialriptide** [comment] 2022-10-11 03:12
Closing due to segfault being fixed up SDL update

**Comment by ankith26** [comment] 2022-10-11 03:19
This is not a bug fixed in

**Comment by ankith26** [comment] 2022-10-11 03:22
The fix to be implemented on the pygame end is that any sound method that needs a chunk, should first check that the chunk is non-NULL (and if it is NULL, raise a `pygame.error` saying the object was not properly initialised)

**Comment by PurityLake** [comment] 2022-10-11 03:35
@ankith26 I'll reopen my PR then, as it does exactly that

**Closed** 2022-10-15 14:35 UTC
Labels: bug, Submodule: mixer, segfault
