### ISSUE TITLE
Pygame package error when installing arducopter tools ‘install-prereqs-ubuntu.sh’ on RPi 4 running ubuntu 20.04 

### ISSUE THREAD

**Issue by AvishkarSeth** [pygame/pygame#3279] opened 2022-07-06 03:04 UTC
```
Collecting pygame
Using cached pygame-2.1.2.tar.gz (10.1 MB)
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -c ‘import sys, setuptools, tokenize; sys.argv[0] = ‘"’"’/tmp/pip-install-v1q2ib17/pygame/setup.py’"’"’; file=’"’"’/tmp/pip-install-v1q2ib17/pygame/setup.py’"’"’;f=getattr(tokenize, ‘"’"‘open’"’"’, open)(file);code=f.read().replace(’"’"’\r\n’"’"’, ‘"’"’\n’"’"’);f.close();exec(compile(code, file, ‘"’"‘exec’"’"’))’ egg_info --egg-base /tmp/pip-install-v1q2ib17/pygame/pip-egg-info
cwd: /tmp/pip-install-v1q2ib17/pygame/
Complete output (29 lines):
WARNING, No “Setup” File Exists, Running “buildconfig/config.py”
Using UNIX configuration…
/bin/sh: 1: sdl2-config: not found
/bin/sh: 1: sdl2-config: not found
/bin/sh: 1: sdl2-config: not found
Traceback (most recent call last):
File “”, line 1, in
File “/tmp/pip-install-v1q2ib17/pygame/setup.py”, line 359, in
buildconfig.config.main(AUTO_CONFIG)
File “/tmp/pip-install-v1q2ib17/pygame/buildconfig/config.py”, line 225, in main
deps = CFG.main(**kwds)
File “/tmp/pip-install-v1q2ib17/pygame/buildconfig/config_unix.py”, line 188, in main
DependencyProg(‘SDL’, ‘SDL_CONFIG’, ‘sdl2-config’, ‘2.0’, [‘sdl’]),
File “/tmp/pip-install-v1q2ib17/pygame/buildconfig/config_unix.py”, line 39, in init
self.ver = config[0].strip()
IndexError: list index out of range
Hunting dependencies…
—
For help with compilation see:
[Compilation - pygame wiki](https://www.pygame.org/wiki/Compilation)
To contribute to pygame development see:
[Contribute - pygame wiki](https://www.pygame.org/contribute.html)
—
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ankith26** [comment] 2022-07-07 07:52
Hi!

This is not a bug with pygame, exactly. 
In your case `pip` is trying to build pygame from source, and failing because of unmet dependencies.

If you are using the aarch64 (64 bit ARM) version of Ubuntu, the pip installer should have picked up our aarch64 release binaries. If it did not, it could mean your pip is at an older version, so you need to upgrade pip first. 

If you are using 32-bit (armhf/armel) Ubuntu (very unlikely, I'm not sure whether this is even a thing now), you can follow [this compilation guide](https://www.pygame.org/wiki/CompileUbuntu) to build pygame from source... or better, upgrade your OS to Ubuntu 22.04 aarch64.

**Comment by ankith26** [comment] 2022-07-09 06:17
I am closing this issue because this is not an issue in the pygame source (my above comment should give you a way to start tackling this, if you have more questions, you can ask on other forums on the internet like reddit, stackoverflow or discord)

If you feel there is something to be fixed on the source side, feel free to re-open this issue with more details ;)

**Closed by ankith26** 2022-07-09 06:17 UTC
Labels: question, needs-op-input
