### ISSUE TITLE
SDL 2.0.22, SDL_mixer 2.6.2, SDL_ttf 2.20.1, SDL_image 2.0.5

### ISSUE THREAD

**Issue by illume** [pygame/pygame#3430] opened 2022-08-28 12:53 UTC
The SDL libs need to be updated to latest versions.

- [ ] windows
- [ ] linux
- [ ] mac (also with manylinux scripts)

Ok, so it seems windows has these versions:
- SDL2-devel-2.0.22-VC.zip (old ahead of manylinux)
- SDL2_image-devel-2.0.5-VC.zip (old same as manylinux)
- SDL2_ttf-devel-2.20.0-VC.zip (latest major but there is a minor update, ahead of manylinux)
- SDL2_mixer-devel-2.6.0-VC.zip (latest major but there is a minor update, ahead of manylinux)

manylinux:
- SDL2-2.0.20.tar.gz
- SDL2_image-2.0.5.tar.gz
- SDL2_ttf-2.0.18.tar.gz
- SDL2_mixer-2.0.4.tar.gz

**Comment by ankith26** [comment] 2022-08-28 15:06
I will try to take this on in the coming week

**Comment by ankith26** [comment] 2022-08-29 06:00
I just tested an update to SDL 2.24.0 and there is still a huge performance regression that I had also observed when I tried to upgrade to SDL 2.0.22 (SDL 2.0.20 works fine)

I use `aliens` example for testing and use Ubuntu 22.04 running under WSL (I mention this because I'm still not sure whether it's a general linux issue, or is specific to my platform)

Some other details that I think are useful for debugging
- `pygame.display.get_driver()` returns `x11` for me, which means `xwayland` is being used under the hood
- Display info gives (this looks aight to me)
```py
>>> pygame.display.Info()
<VideoInfo(hw = 0, wm = 1,video_mem = 0
         blit_hw = 0, blit_hw_CC = 0, blit_hw_A = 0,
         blit_sw = 0, blit_sw_CC = 0, blit_sw_A = 0,
         bitsize  = 32, bytesize = 4,
         masks =  (0x00ff0000, 0x0000ff00, 0x000000ff, 0x00000000),
         shifts = (16, 8, 0, 0),
         losses =  (0, 0, 0, 8),
         current_w = 300, current_h = 300
         pixel_format = SDL_PIXELFORMAT_RGB888)
```
For now I'll be testing whether I can somehow compile wayland support in in our manylinux base images, and see if that works as a fix for this issue as well. Later I may make an SDL issue on this once I can collect some more info

**Comment by Starbuck5** [comment] 2022-08-31 04:09
The SDL_Image update will be harder than the rest, I predict, so that can wait.

**Comment by illume** [comment] 2022-09-13 13:02
Now SDL and SDL_image need updating. Probably to SDL 2.24.0, SDL_image 2.6.2.

**Comment by ankith26** [comment] 2022-09-13 13:59
> The SDL_Image update will be harder than the rest, I predict, so that can wait.

Actually it won't be much harder, I will be putting up a PR for that in a few days hopefully. The real problem is SDL itself, for reasons I've already mentioned earlier.

As a worst-case resort, we might have to downgrade SDL to 2.0.20 on windows. Or just leave it as is (with the version inconsistency) if it does not have obvious breaks

**Comment by illume** [comment] 2022-09-18 11:20
There's a strange err on windows appveyor tests. Just gives an error code, no failed test or crash is visible in the log.

**Comment by MyreMylar** [comment] 2022-09-18 17:03
> There's a strange err on windows appveyor tests. Just gives an error code, no failed test or crash is visible in the log.

I tried running this branch locally on windows and it seems fine, all the tests pass and I can run various pygame programs without obvious errors. Not sure what issue appveyor is having.

**Comment by ankith26** [comment] 2022-10-16 12:03
We now have consistent SDL-and-friends versioning on all the dependencies zero-ed in for the release. It was decided that SDL and SDL_image won't be at the latest release this pygame release (due to issues, elaborated in the relevant PRs)

Thanks everyone!

**Closed by ankith26** 2022-10-16 12:03 UTC
Labels: dependencies, buildconfig, manylinux
