### ISSUE TITLE
draw.polygon slower in 2.1.2 than in 1.9.6

### ISSUE THREAD

**Issue by hpnok** [pygame/pygame#3135] opened 2022-04-14 04:16 UTC
Recently I've noticed that an algo I made a while ago had become noticeably slow, so I plugged a profiler and found out that calls made to `pygame.draw.polygon` were causing my issue. Since I did not notice performance problems back then, I compared its speed with an older version of pygame.

```
$python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>import pygame
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
>>>import timeit
>>>setup = """from random import randint
... import pygame
... import pygame.gfxdraw
... surf = pygame.Surface((120, 64))
... def half_triangle_poly(surface: pygame.Surface, multiplier: int):
...     w, h = surface.get_size()
...     top_left = (w*(1 - multiplier), h*(1 - multiplier))
...     top_right = (w*multiplier, top_left[1])
...     bottom_left = (top_left[0], h*multiplier)
...     return [top_left, top_right, bottom_left]
... """
>>>for scale in range(1, 9):
...    print(timeit.timeit(stmt=f'pygame.draw.polygon(surf,(128, 0, 255), half_triangle_poly(surf, {scale}))',
                           setup=setup, number=10000))
0.13838968499999993
0.21100721700000236
0.3219181770000006
0.4155462180000029
0.5251170810000048
0.6205457520000053
0.730503971999994
0.8374572599999937
```

```
$python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame 2.1.2 (SDL 2.0.18, Python 3.7.0)
Hello from the pygame community. https://www.pygame.org/contribute.html
# same setup
>>>for scale in range(1, 9):
...    print(timeit.timeit(stmt=f'pygame.draw.polygon(surf,(128, 0, 255), half_triangle_poly(surf, {scale}))',
                           setup=setup, number=10000))
0.5657153599999987
2.387819206000003
5.963148969999992
11.077614591
17.871329568999997
26.282841297000004
36.43204714100003
48.14373332600002
```

Note that performance degradation seems worst when drawing a lot of stuff outside the surface's clip.

As mentioned in #3019 I've switched to `gfxdraw` and the performance is back to something similar to what I had in 1.9.6

**Comment by ankith26** [comment] 2022-04-14 04:49
Hi, thanks for reporting the issue! 
Since this is a known issue and is already being tracked by the PR you linked, I'll close this issue because a similar issue already exists, but feel free to report any new related findings under that issue ;)

**Comment by Starbuck5** [comment] 2022-04-14 05:55
I can replicate your testing locally.

I think the slowdown is actually scaling by polygon perimeter, rather than amount outside clip area. Perhaps we changed our polygon algorithm between pygame 1.9.6 and pygame 2.0.0

**Comment by Starbuck5** [comment] 2022-04-15 00:39
@MightyJosip on discord says:

> Ok noticed that in line 2260, 2306 and 2325 draw_line should be changed with drawhorzlineclipbounding. Latter function is way more optimized for that specific case

Re-opening this as it is a specific performance regression with a specific fix that is completely independent to the other draw.polygon performance issue - which is really just a performance suggestion.

**Closed** 2022-04-15 14:39 UTC
