### ISSUE TITLE
Event system is too slow for key presses

### ISSUE THREAD

**Issue by fortwoone** [pygame/pygame#2871] opened 2021-11-27 17:26 UTC
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 7
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.6
- **SDL version** (e.g. SDL 2.0.12): 2.0.16
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.1.0

**Current behavior:**

A key needs to be pressed and released twice if you release it too fast (pygame won't post KEYUP events), so this forbids key-mashing implementations (and the delay is even too long to allow players to repeat actions even though the command doesn't require key mash !).
**Expected behavior:**

No matter the speed of the key mash, it is always caught by pygame.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Press a key and release it the moment after you pressed it.
2. If you make a dictionary containing every single key press, you'll find out that the key you just pressed and released is still considered pressed (True).

**Comment by ankith26** [comment] 2021-11-28 03:03
Can't reproduce this problem on Windows 11. I used a minimal test code
```py
import pygame

pygame.init()
pygame.display.set_mode((400, 300))

key_pressed = 0
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            print("This should be zero!", key_pressed)
            raise SystemExit()

        if event.type == pygame.KEYDOWN:
            key_pressed += 1
            print(event)

        if event.type == pygame.KEYUP:
            key_pressed -= 1
            print(event)
```
I mash many keys simultaneously, also quickly press and release keys, and the events are printed right, and also at the end, `key_pressed` is `0` which indicates all `KEYDOWN` events have got their corresponding `KEYUP` events, so the bug you describe does not happen. This was a pygame bug in 2.0.0, but was patched in 2.0.1. I think the problem here might lie in the code you used, or if that's not the case, a problem in the underlying platform, windows 7 is quite out of date now.

**Comment by novialriptide** [comment] 2021-11-28 03:53
I think your keyboard is the issue, have you tried a different one? The keys might not be working properly.

**Comment by MyreMylar** [comment] 2021-11-28 08:54
It does sound like a potential variant of the classic rollover issue again, it rears it's head every so often on here because of people using WASD keys and other more than three at a time combos:

https://en.wikipedia.org/wiki/Rollover_(keyboard)

Basically unless you have an 'n-key rollover' keyboard (generally a higher end mechanical keyboard) there is a limit to what your keyboard can handle. You can get ghost key events and missed key events because the keyboard isn't able to cope. 

Could be something else but I would rule this out first. Ideally by buying a nice fancy clacky keyboard because everyone should have one :)

**Comment by MyreMylar** [comment] 2021-11-28 08:55
I also tried @ankith26 's code above and couldn't see any issue repeatedly hammering the same key for several minutes. I tried different keys and there was no obvious issue. Though I do have a fancy keyboard.

**Comment by ankith26** [comment] 2021-11-28 09:15
👍 
I think we've established that this is not a pygame issue, closing this issue :)

**Closed by ankith26** 2021-11-28 09:15 UTC
Labels: bug
