### ISSUE TITLE
Colab compatibility

### ISSUE THREAD

**Issue by chsher** [pygame/pygame#2463] opened 2021-01-29 16:53 UTC
Hello, thank you for this great tool. Is there a workaround to have pygame be compatible with Google Colab?

**Comment by MyreMylar** [comment] 2021-01-30 14:42
I just had a go at running it and it looks like pygame installs fine on Google Colab and can run some programs.

It depends what you want to do with it though as Google Colab has the big drawback of not having a video display device (and I'm guessing no audio device either), it's just a bunch of servers. There's no multimedia hardware for pygame to interface with.

Probably you could load some images into surfaces in memory and goof about with them?

Test program I used for Google Colab:

```
!pip install pygame

import pygame

pygame.init()

running = True

test_surf = pygame.Surface((100, 200), depth=32)

test_surf.fill((255, 50, 200), pygame.Rect(0,0,50,200))
test_surf.fill((20, 190, 70), pygame.Rect(50,0,50,200))


pixel_col_1 = test_surf.get_at((25, 50))
pixel_col_2 = test_surf.get_at((75, 50))

print('Pixel colour 1: ', pixel_col_1)
print('Pixel colour 2: ', pixel_col_2)
```

**Comment by MyreMylar** [comment] 2021-01-30 14:59
Just for fun I tried to get some visual output from it as well:

```
!pip install pygame

import pygame
import random
from IPython.display import Image


pygame.init()


running = True

test_surf = pygame.Surface((100, 100), depth=32)


test_surf.fill((random.randrange(0,255),
                random.randrange(0,255),
                random.randrange(0,255)), pygame.Rect(0,0,50,200))
test_surf.fill((random.randrange(0,255),
                random.randrange(0,255),
                random.randrange(0,255)), pygame.Rect(50,0,50,200))

pixel_col_1 = test_surf.get_at((25, 50))
pixel_col_2 = test_surf.get_at((75, 50))

pygame.image.save(test_surf, 'test_image.png')

Image('test_image.png', embed=True)
```

**Comment by pleabargain** [comment] 2021-08-18 08:14
I got the above to work here:
https://colab.research.google.com/drive/1lMkY0kk-6oEVaxMnvbvh09UZpnadjZgf?usp=sharing

reproducible results! :)

**Comment by Starbuck5** [comment] 2022-07-16 08:38
Hopefully other people can get insights from this thread, but I'm going to go ahead and close the issue.

I think it's more of a "cant fix" than a "wont fix"

**Closed** 2022-07-16 08:38 UTC
Labels: feature request, misc portability
