### ISSUE TITLE
Loops parameter in pygame.mixer.music.play() does not work for MIDI

### ISSUE THREAD

**Issue by b1a0** [pygame/pygame#1908] opened 2020-06-03 18:54 UTC
The behavior of pygame.mixer.music.play() is different if you play an .mp3 or a .mid file, where mp3s will be looped properly and MIDI files will only be played once.

The version is 1.9.6.

**Comment by MightyJosip** [comment] 2020-06-04 08:52
Try to install pygame with `pip install pygame==2.0.0.dev10` and then see if you still got that problem

**Comment by MyreMylar** [comment] 2020-06-04 19:21
If the problem is not fixed by pygame 2 then a copy of the midi file would be useful and information on what platform you are on.

**Comment by b1a0** [comment] 2020-06-04 21:53
I'm sorry, it seems like I am not able to test pygame2 straightaway, when I try to install I get this:

```
Traceback (most recent call last):
  File "sound_test.py", line 17, in <module>
    mixer.music.load("//home/myname/dev/music_app/87216.mid")
pygame.error: Couldn't open /etc/timidity/freepats.cfg
```
This file does not exist on my computer. Might be unrelated with the original question, but maybe still helpful for you?

I am on Ubuntu 20.04 LTS. On pygame 1.9.6 I tried several midi files, some created by myself, some downloaded from the internet. If you can test it easily in pygame2, I would appreciate the help.

Minimal example for creation of midi (through mingus, `pip install mingus`) and playing - but you can really just take any .mid file, I did not find one that works:

```
from pygame import mixer

from mingus.containers import Track
from mingus.midi import midi_file_out

# path were MIDI file one_note.mid will be created
filepath = "/home/myname/dev/myproject/one_note.mid"

# generate track containing one whole note (4 beats long)
t = Track()
t.add_notes("C-4", 1)  
midi_file_out.write_Track(filepath, t, bpm=120)

mixer.init()
mixer.music.load(filepath)
mixer.music.play(loops=2)

while True:

    print("Press 'p' to pause, 'r' to resume")
    print("Press 'e' to exit the program")
    query = input("  ")

    if query == 'p':

        # Pausing the music
        mixer.music.pause()
    elif query == 'r':

        # Resuming the music
        mixer.music.unpause()
    elif query == 'e':

        # Stop the mixer
        mixer.music.stop()
        break

```

**Closed** 2020-06-07 08:16 UTC
Labels: mixer.music, needs-op-input
