### ISSUE TITLE
pygame.event.peek() seems to strip the user provided attributes to event type pygame.USEREVENT (+)

### ISSUE THREAD

**Issue by ipinsel** [pygame/pygame#2459] opened 2021-01-22 21:44 UTC
pygame 2.0.0 (SDL 2.0.12, python 3.8.6)

**Current behavior:**

for all the event types >= the pygame.USEREVENT

```
pygame.event.post( pygame.event.Event( pygame.USEREVENT, { "value": value } ) )
if pygame.event.peek():
  for event in pygame.event.get():
    if event.type == pygame.USEREVENT:
      print( event )
```

prints <Event(32774-UserEvent {'code': -559038737})>
if you replace the the pygame.event.peek() with True, the behavior is correct as expected below

**Expected behavior:**

prints <Event(32774-UserEvent {'value': value})>

**Comment by ankith26** [comment] 2021-01-23 07:52
I’m away from my PC ATM, but if I remember correctly, I have tested this function and it was working. Could you try upgrading to pygame 2.0.1 and see if the issue persists (2.0.1 changed a few things, pygame.event related, so maybe this has been fixed)

**Comment by ankith26** [comment] 2021-01-23 09:10
I could reproduce this bug with pygame 2.0.0. So thanks for the bug report! But this bug does not appear on pygame 2.0.1

I used the following code
```python
import pygame
pygame.init()

pygame.event.clear()
pygame.event.post(pygame.event.Event(pygame.USEREVENT, {"value": 1}))
if pygame.event.peek():
    for event in pygame.event.get():
        if event.type == pygame.USEREVENT:
            print(event)
pygame.quit()
```

And output
```
>>> %Run test1.py
pygame 2.0.0 (SDL 2.0.9, python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
<Event(32774-UserEvent {'code': -559038737})>
>>> %Run test1.py
pygame 2.0.1 (SDL 2.0.9, Python 3.7.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
<Event(32847-UserEvent {'value': 1})>
```

So this issue looks like its fixed. I'll leave this issue open until you can confirm that upgrading to 2.0.1 fixes the problem for you as well.

**Comment by ipinsel** [comment] 2021-01-23 11:17
this test program now worked, my main application crashed, but only the first time, i think i might have kept it running while i upgraded the pygame, when i closed everything and reopened after that no issues so far with the peek.

**Comment by ankith26** [comment] 2021-01-23 13:37
Nice to hear it’s working now. Closing this issue

**Closed by ankith26** 2021-01-23 13:37 UTC
Labels: bug
