### ISSUE TITLE
Consider adding sub millisecond Clock to timer module for SDL2

### ISSUE THREAD

**Issue by Lobsternator** [pygame/pygame#2177] opened 2020-10-12 09:10 UTC
- **Operating system** : Widnows 10
- **Python version** : 3.7.3
- **SDL version** : 2.0.12
- **PyGame version** : 2.0.0.dev14

The `Clock.tick_busy_loop` function is consistently too fast for the target fps. `Clock.get_fps()` consistently measures around 62.5 fps when I pass in 60 as the target fps and a manual measurent using `time.perf_counter` is even faster (~65 fps). For clarification, the manual measurement is an average taken over the span of two seconds.

**Test code**

```
import sys, time, pygame
pygame.display.init()

size = width, height = 320, 240
screen = pygame.display.set_mode(size)
clock = pygame.time.Clock()
fps = 60
measures = []

while True:
    start = time.perf_counter()
    for event in pygame.event.get():
        if event.type == pygame.QUIT: sys.exit()
        
    clock.tick_busy_loop(fps)
    end = time.perf_counter()

    measures.append(1 / (end - start))
    if len(measures) > fps * 2:
        del measures[0]

    print(f"manual: {sum(measures) / len(measures)}, pygame: {clock.get_fps()}")
    pygame.display.flip()
```

**Comment by MyreMylar** [comment] 2020-10-12 10:02
I don't think `busy_loop()` is perfectly accurate, but your start & end are in the wrong place surely? `clock.tick_busy_loop(fps)` delays based on the time since it was last called, but your timing test is excluding the time taken to do all of this:

```
    measures.append(1 / (end - start))
    if len(measures) > fps * 2:
        del measures[0]

    print(f"manual: {sum(measures) / len(measures)}, pygame: {clock.get_fps()}")
    pygame.display.flip()
```

...in the loop. So I would expect the delay to be less than required for 60FPS because `print()` is usually fairly slow at least and is going to eat into some of the frame time, reducing the amount of time `busy_loop()` would need to delay. You'd be better using start and end to capture the whole loop, and perhaps recording your data each loop instead of printing it - and then produce a timing report at the end when you have quit out of the loop.

**Comment by Lobsternator** [comment] 2020-10-12 22:52
Oh, I see. How about this then? When I do this `Clock.get_fps()` reads the same as the manual measurement.

```
import sys, time, pygame
pygame.display.init()

size = width, height = 320, 240
screen = pygame.display.set_mode(size)
clock = pygame.time.Clock()
fps = 60
measures = []
t = 0
last_t = 1/fps

while True:
    t = time.perf_counter()
    for event in pygame.event.get():
        if event.type == pygame.QUIT: sys.exit()
        
    measures.append(1 / (t - last_t))
    if len(measures) > fps * 2:
        del measures[0]
    print(f"manual: {sum(measures) / len(measures)}, pygame: {clock.get_fps()}")
    
    pygame.display.flip()

    clock.tick_busy_loop(fps)
    last_t = t
```

Also is there any way to increase the accuracy of `Clock.tick_busy_loop`? It seems that it is consistently 2.5 fps off at 60 fps, I feel like because it is so consistent there has to be some variable that's not being accounted for.

**Comment by MyreMylar** [comment] 2020-10-13 08:47
If you try playing around with some different FPS values you'll notice that its very accurate on some values e.g. 50FPS is bang on, as is 100 FPS. But some values are much further out. E.g. 150FPS always produces 166FPS for me. 

While the errors get bigger as the FPS target gets bigger, the fact that the error size jumps around (e.g. 58 FPS is pretty accurate compared to 60 FPS) suggests it's caused by rounding.

Indeed if you follow the calculation in `time.c`:

https://github.com/pygame/pygame/blob/1f1a71c2bda3a6b7a049ffc4943484e244087ab5/src_c/time.c#L289-L312

You'll see that the input FPS goes into this line:

`int delay, endtime = (int)((1.0f / framerate) * 1000.0f);`

Which with a value of 60 FPS gets you 16.66666666666666 ms recurring, rounded down to 16ms. I could change this to round up the other way to 17ms (I tried it) but the inaccuracy is nearly the same the other way with 60FPS giving you a value of 58.8FPS.

Ultimately, there is only millisecond level accuracy in the SDL functions pygame is using to calculate time passing and you would need sub millisecond accuracy to get exactly 60FPS.

I did a quick test into using:

https://wiki.libsdl.org/SDL_GetPerformanceCounter
https://wiki.libsdl.org/SDL_GetPerformanceFrequency

Which are SDL2 only functions that provide platform specific timing at higher accuracy and was able to get the 60 FPS timer to report 59.9 FPS in your test case on windows, so there might be an option there to create a new, SDL2 only function that used those counters but that would likely need a bit of work to figure out what accuracy we were getting on different platforms and work out all the kinks.

**Comment by MyreMylar** [comment] 2020-10-13 08:53
**Potential To Do for SubMS Accuracy Clock class in SDL2**

- [ ] Create list of regular Clock methods to port over.
- [ ] Investigate values reported by `SDL_GetPerformanceFrequency()` on main platforms (mac, windows, debian/ubuntu linux) to determine general accuracy of the Clock.
- [ ] Create base implementation.
- [ ] Port regular clock tests over.

**Comment by MightyJosip** [comment] 2020-10-13 08:54
If someone wants to start working on it I did something in the past (#1659)

**Comment by MyreMylar** [comment] 2020-10-13 11:19
Related: https://github.com/pygame/pygame/issues/304

**Comment by ankith26** [comment] 2020-10-16 15:46
I have made a pr for this, #2188, but that PR has to wait for a post2.0.0 version to be merged.

**Comment by ankith26** [comment] 2021-12-31 05:04
I'll just close this issue for now because #304 exists to track this issue. I'm hoping to revive my PR for fixing this in 2.2

**Closed by ankith26** 2021-12-31 05:04 UTC
Labels: enhancement, time, Experimental
