### ISSUE TITLE
fopen() fails on Windows for non-ANSI characters

### ISSUE THREAD

**Issue by shenjia** [pygame/pygame#645] opened 2018-11-27 22:49 UTC
I use windows 10 with a Chinese username '运城国际学校', the desktop dir will display as "C:\Users\运城国~1\Desktop" in command line or use `os.getcwd()`.

While I try to load a font file which store in this path by:

```
root = os.getcwd() # C:\Users\运城国~1\Desktop\Test
fontfile = os.path.join(root, 'test.ttf')
pygame.font.Font(fontfile, 32)
```

I got this error [OSError: unable to read font file 'C:\Users\运城国~1\Desktop\Test\test.ttf']

I can use `os.listdir()` to location this font file, and it works well if I move this file to `c:\test`. So the font file have no problem at all. It must be something wrong to location this file in `pygame.font.Font`.

Since I can load images, audios from the same UTF-8 path, except fonts. Maybe there are different ways to location file between load image / audios and load fonts?

I have to use this UTF-8 path, because I want to package my game with Pyinstaller. It will automaticly extract everything to Temp directory which is in user's home directory.

**Comment by dlon** [comment] 2018-11-28 16:01
I think fopen() doesn't work with UTF-8? At least on Windows. And I don't know if this is true any longer, but Windows apparently only accepts UTF-16 paths.

https://github.com/pygame/pygame/blob/e987de7999bf347f19a6c6d5ecc16964bba20eab/src_c/font.c#L666-L686

**Comment by dlon** [comment] 2018-11-28 16:23
Actually, this is already being used, but it returns an incorrect result?
https://github.com/pygame/pygame/blob/e987de7999bf347f19a6c6d5ecc16964bba20eab/src_c/rwobject.c#L170-L259

**Comment by dlon** [comment] 2018-11-28 16:33
Okay the problem really is fopen() on Windows.
Solution: I think we must use `_wfopen()` on Windows.

**Comment by dlon** [comment] 2018-11-29 01:00
Duplicate of #196

**Closed** 2018-12-06 14:17 UTC
Labels: Windows

**Comment by illume** [comment] 2018-12-10 08:29
Hi,

if you're on windows you can download from the appveyor page: https://ci.appveyor.com/project/pygame/pygame
- click on the python version you use, either 32bit or 64bit
- then click on "Artifacts" tab
- download the .whl file.
- install the .whl file with `pip install pygame-1.9.5.dev0-cp36-cp36m-win32.whl`

Compiling it yourself is very easy on other platforms.
https://www.pygame.org/wiki/Compilation
