### ISSUE TITLE
Fatal Python error upon playing multiple sounds

### ISSUE THREAD

**Issue by esidebo** [pygame/pygame#1092] opened 2019-06-04 07:03 UTC
With Python 3.5.2 (inside an Ubuntu-based Docker container) and pygame 1.9.6 I run the simple script below, where I try to play a sound on top of another using different channels in the pygame.music.mixer. When the shorter, second, sound has finished playing the program crashes with the error `Fatal Python error: take_gil: NULL tstate` -> `Aborted`. 

I guess this might be a Python (threading?) issue since I don't have this problem on my Mac with Python 3.7.3 (same pygame version). It's not easy for me to change the python version in my application though. Any suggestions as how to solve or work around?

```
import pygame
pygame.mixer.pre_init()
pygame.mixer.init()
pygame.init()

sound_bkg_music = pygame.mixer.Sound("./data/music/ImperialMarch60.wav")
sound_effect = pygame.mixer.Sound("./data/music/StarWars3.wav")

pygame.mixer.Channel(0).play(sound_bkg_music)
pygame.mixer.Channel(1).play(sound_effect)
```

**Related Docs**: https://www.pygame.org/docs/ref/mixer.html

**Comment by robertpfeiffer** [comment] 2019-11-04 14:59
I could not *quite* reproduce this, but I get

> ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred

when I run your example on Python 2.7 and pygame-2.0.0-dev6, but not with Python 3.6

**Comment by nthykier** [comment] 2020-04-27 21:07
For what it is worth, I cannot reproduce this either.  (Tried both 1.9.6 and 2.0.0.dev7 with python3.8). I noticed that others that had this variant of the error code fixed it with a linker option rather than a code change (https://github.com/dgrunwald/rust-cpython/issues/142), which suggest we might be looking at a tooling issue rather than a code issue.

**Comment by ankith26** [comment] 2020-10-03 05:10
I had opened a similar issue recently (#2106 which is closed now) and it turns out, the issue is same as mine. The cause of this issue is python 3.5 on linux, not pygame. Even in my case 2 sounds were playing at the same time. 

An upgrade to a newer python version easily fixes this issue, but in the case of OP I don't think thats an option (OP asked about a year ago, so things do not matter now, do they?)

**Comment by MyreMylar** [comment] 2020-10-03 12:46
Yeah I've also read up on this GIL issue in the past. I'll close it as python 3.6+ have been out for a long time now. If anyone else encounters it: upgrade your python and get back to us if you still have the problem.

**Closed by MyreMylar** 2020-10-03 12:46 UTC
Labels: Difficulty: moderate, Docker, Gnu/Linux, mixer
