### ISSUE TITLE
MP3 does not work after upgrade of Pygame 1.9.6 -->  2.0.0

### ISSUE THREAD

**Issue by dakshsriv** [pygame/pygame#2419] opened 2020-12-23 21:50 UTC
**Environment:**

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):
```
$ cat /etc/os-release
NAME="elementary OS"
VERSION="5.1.7 Hera"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.1.7 Hera"
LOGO=distributor-logo
VERSION_ID="5.1.7"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/os/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=hera
UBUNTU_CODENAME=bionic
```

- **Python version** (e.g. 3.7.9, 3.8.5) :
```
$ python3 -V
Python 3.6.9
```
- **SDL version** (e.g. SDL 2.0.12):
```
$ sudo apt search python3 |grep -i sdl
python3-sdl2/bionic,bionic,now 0.9.3+dfsg2-1 all [installed]
  Python bindings to the SDL2 C-library (Python 3 build)
$ pip3 list
pip (9.0.1)
pkg-resources (0.0.0)
pygame (2.0.0)
PySDL2 (0.9.7)
PySimpleGUI (4.32.1)
setuptools (39.0.1)
```

- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):
2.0.0

- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it):
Lenvo Thnkpad bult-in audio. Works in other programs.
I even made a program using PySDL library to play sound and that works.
Only PyGame fails to play.

**Current behavior:**

My environment  had Pygame 1.9.6 before.  upgraded to Pygame 2.0.0 and after the upgrade mp3 playback is not working.
```
$ python3 audiot.py
pygame 2.0.0 (SDL 2.0.12, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "audiot.py", line 5, in <module>
    mixer.music.load(file)
pygame.error: Unrecognized audio format
```

**Expected behavior:**

```
$ python3 audiot.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
```
< sound plays>

**Screenshots**

If applicable, copy and paste screenshots to help explain your problem.

**Steps to reproduce:**

Please explain the steps required to duplicate the issue, especially if you are able to provide a sample application.
if the bug is caused by a specific file (image, font, sound, level, please upload it as an attachment

1. Initialize the PyGame mixer.
2. With a test MP3 file in the same folder, add a line of code to load the sound.
3. Add a line to play the sound, and run the file.

**Test code**

```
from pygame import mixer

file = 'sample.mp3'
mixer.init()
mixer.music.load(file)
mixer.music.play(0)
```

The audio file details (  tried multiple files actually)
```
$ file sample.mp3
sample.mp3: Audio file with ID3 version 2.4.0, contains:MPEG ADTS, layer III, v1,  64 kbps, 44.1 kHz, Stereo
$ aplay sample.mp3
Playing raw data 'sample.mp3' : Unsigned 8 bit, Rate 8000 Hz, Mono
```

**Comment by illume** [comment] 2020-12-25 19:14
Thanks for the issue report.

I think it's maybe a duplicate of this issue about mp3 as well: https://github.com/pygame/pygame/issues/2399

**Comment by dakshsriv** [comment] 2020-12-26 23:35
Ummm... I do not claim to know much about this but I am thinking it might not be a duplicate.
For example, in #2399 , the error message is
`pygame.error: Unable to open file`

However, in my case, the error message is different:
`pygame.error: Unrecognized audio format`

**Comment by ankith26** [comment] 2020-12-27 04:00
I am inclined to think that it is an SDL issue. Haven’t done much research on it, but found this in the changelog of the most recent SDL_Mixer version (2.0.5, which hasn’t been released yet)
```
David Gow - Fri Oct 23 23:01:00 2020
 * Fixed mp3 file detection.
```

**Comment by sulix** [comment] 2021-01-30 07:28
FYI: I doubt the SDL_Mixer mp3 file detection issue is what you're looking for here. It only affected some very specific mp3 files — MPEG 2/2.5 layer 3 files which don't have ID3 tags. Since the sample.mp3 listed in the initial report is a v1 file, with an ID3 tag, it satisfies neither of the triggering conditions for that bug.

The full upstream bug report for that issue can be found here: https://bugzilla.libsdl.org/show_bug.cgi?id=5322

But, in summary, I'm reasonably sure you're seeing a separate issue.

**Comment by llindstrom** [comment] 2021-03-01 05:25
The problem is that SDL2_mixer is not built with mp3 support for the manylinux1 wheel. I believe the problem is with [pygame/buildconfig/manylinux-build/docker_base/sdl_libs/build-sdl2-libs.sh](https://github.com/pygame/pygame/blob/main/buildconfig/manylinux-build/docker_base/sdl_libs/build-sdl2-libs.sh).

```bash
# Build SDL_mixer
tar xzf ${MIX2}.tar.gz
cd $MIX2
# The --disable-x-shared flags make it use standard dynamic linking rather than
# dlopen-ing the library itself. This is important for when auditwheel moves
# libraries into the wheel.
./configure \
      --disable-dependency-tracking \
      --disable-music-flac-shared \
      --disable-music-midi-fluidsynth \
      --disable-music-midi-fluidsynth-shared \
      --disable-music-mod-mikmod-shared \
      --disable-music-mod-modplug-shared \
      --disable-music-mp3-mpg123 \
      --disable-music-mp3-mpg123-shared \
      --disable-music-ogg-shared \
      --enable-music-mod-mikmod \
      --enable-music-mod-modplug \
      --enable-music-ogg \
      --enable-music-flac \
      --enable-music-mp3 \
      --enable-music-mod \
```

It contains `--disable-music-mp3-mpg123` but only has `--enable-music-mp3`, which defaults to the mad library. Try removing the disable and add `--enable-music-mp3-mpg123`.

**Comment by Starbuck5** [comment] 2021-09-10 08:37
I've experienced this on Mac, so mp3s with mixer.music only work fine on Windows.

Since we do mac from homebrew, we follow their formula, which disables music-mp3-mpg123. See https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/sdl2_mixer.rb

This comment has a solution: https://github.com/veandco/go-sdl2/issues/299#issuecomment-611681191

I wonder if homebrew would accept a patch that un-disables mp3 by default. Maybe it was that way while libmp3 was in copyright, and it recently expired?

**Comment by ankith26** [comment] 2021-10-17 04:36
MP3 should be supported on Mac and Linux now, after pygame v2.0.2, so closing this issue.
If some issues still persist feel free to re-open, or open a new PR

**Closed by ankith26** 2021-10-17 04:36 UTC
Labels: bug, mixer.music, macosx, manylinux
