### ISSUE TITLE
event.get(type or sequence) does not work as expected

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#2319] opened 2020-11-12 16:33 UTC
`pygame.event.get(type or sequence)` is supposed to return a list of all such events from the event queue for the user to iterate over, using a `for` loop.

Ref docs: https://www.pygame.org/docs/ref/event.html#pygame.event.get

Currently broken on pygame 2, with SDL2. Here is some sample code
```python
import pygame
pygame.init()
pygame.display.set_mode((500, 500))

while True:
    pygame.time.delay(1000)
    print(pygame.event.get(pygame.MOUSEMOTION))
    if pygame.event.peek(pygame.QUIT):
        break
pygame.quit()
```

Sample output with pygame 2 (moving the mouse around the screen)
```
[<Event(1024-MouseMotion {'pos': (249, 141), 'rel': (3, 3), 'buttons': (0, 0, 0), 'window': None})>]
[<Event(1024-MouseMotion {'pos': (134, 362), 'rel': (2, 3), 'buttons': (0, 0, 0), 'window': None})>]
[<Event(1024-MouseMotion {'pos': (76, 89), 'rel': (1, 2), 'buttons': (0, 0, 0), 'window': None})>]
[<Event(1024-MouseMotion {'pos': (302, 83), 'rel': (4, 3), 'buttons': (0, 0, 0), 'window': None})>]
[<Event(1024-MouseMotion {'pos': (287, 396), 'rel': (2, 1), 'buttons': (0, 0, 0), 'window': None})>]
```

As you can clearly see, no matter how many MOUSEMOTION EVENTS happened within the call to pygame.event.get(), it returns a list with only one event.

Output with pygame 1.9.x (output gets really huge, so posting just a small part here)
```
[<Event(4-MouseMotion {'pos': (18, 99), 'rel': (18, 99), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 101), 'rel': (0, 2), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 103), 'rel': (0, 2), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 106), 'rel': (0, 3), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 107), 'rel': (0, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 108), 'rel': (0, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 109), 'rel': (0, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 110), 'rel': (0, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 111), 'rel': (0, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (18, 113), 'rel': (0, 2), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (17, 114), 'rel': (-1, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (17, 116), 'rel': (0, 2), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (16, 117), 'rel': (-1, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (15, 118), 'rel': (-1, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (14, 119), 'rel': (-1, 1), 'buttons': (0, 0, 0)})>, <Event(4-MouseMotion {'pos': (14, 120), 'rel': (0, 1), 'buttons': (0, 0, 0)})>,
```

Anyways, identified the issue myself, and worked on the fix, PR coming soon :) 

Opened the issue, since it is nice to keep track of bugs, just incase my PR doesnt quite work out.

**Comment by ankith26** [comment] 2020-11-13 10:59
Here's a simpler test case, incase the above example was not so clear
```python
# post 10 userevents
for i in range(10):
    pygame.event.post(pygame.event.Event(pygame.USEREVENT))

# supposed to return a list of all 10 posted userevents, but returns a list
# of only one event
print(pygame.event.get(pygame.USEREVENT))
```

**Comment by robertpfeiffer** [comment] 2020-11-18 08:15
Thank you so much for finding this. I am using this feature extensively. This is relevant when translating touch events into keyboard events.

**Comment by illume** [comment] 2020-12-17 17:41
Seems the event refactor branch returns a list, but not with all of the items in there.

Here's a reproducer...
```bash

python -c '
import pygame
pygame.init()
# post 10 userevents
for i in range(10):
    pygame.event.post(pygame.event.Event(pygame.USEREVENT))

# supposed to return a list of all 10 posted userevents, but returns a list
# of only one event
assert len(pygame.event.get(pygame.USEREVENT)) == 10
'
```

**Comment by ankith26** [comment] 2020-12-17 17:43
That’s probably because OS sends other events to pygame. And in the reproducer, the display mode is not set. Which is a requirement for posting events

**Comment by illume** [comment] 2020-12-17 18:35
Note, this issue isn't blocking the event refactor branches being merged.

**Comment by ankith26** [comment] 2020-12-18 03:18
The testcase you put does not reproduce for me. Maybe its some setup issue from your end. Noticed you are using `python` instead of `python3`. So hopefully you have my PR branch and pygame on the same version

**Comment by illume** [comment] 2020-12-18 15:28
You're right! It's working for me too. I must have installed the wrong one when testing somehow.

Thanks @ankith26 Closing because it's fixed in https://github.com/pygame/pygame/pull/2398

**Closed by illume** 2020-12-18 15:28 UTC
Labels: Difficulty: Easy, bug, confirmed/reproducible, critical
