### ISSUE TITLE
A visual glitch with pygame 

### ISSUE THREAD

**Issue by RickyAsbury** [pygame/pygame#2710] opened 2021-09-10 14:39 UTC
My issue is that my code skips a line of code that is suppose to fix a visual glitch inside the game I’m working on and it’s being stubborn I looked for mistakes and I even looked at the y cordinent itself via console but it’s weird because the console reads it correctly just pygame dosen’t output it correctly I wonder if it’s pygame or my computer since I’m using the surface pro x

**Comment by Starbuck5** [comment] 2021-09-10 19:49
Python doesn't skip lines of code.

This issue tracker is for issues with pygame itself, not issues that any one person has while writing their program, so I'm going to close this.

I would like to help anyways, but you've presented a description of what you think the problem is, without any code or screenshots or anything to go off. Maybe you don't understand that in pygame y=0 is the top of the screen?

You can ask for help on r/pygame, stackoverflow, or the pygame community discord (discord.gg/pygame).

**Closed by Starbuck5** 2021-09-10 19:49 UTC

**Comment by RickyAsbury** [comment] 2021-09-11 15:19
Alright I guess I’ll just show you my code but can you tell me that you won’t use it for any personal gain

**Comment by MyreMylar** [comment] 2021-09-12 07:49
I think that can be absolutely guaranteed.

**Comment by RickyAsbury** [comment] 2021-09-14 00:13
Alright I just got my surface pro x factory reseted due to drivers Im going to send the code tomorrow probably after 12pm

**Comment by RickyAsbury** [comment] 2021-09-14 16:22
I'm going to need a bit because I don't know how to upload a file via github

**Comment by RickyAsbury** [comment] 2021-09-14 17:56
https://1drv.ms/u/s!AqOGPQv_OzF7nzpnawMzowA8TjnF?e=W4aMiF
here's the link to my file I created for my game currently it has place holders and you'll need pygame-menu or else the code won't run

**Comment by Starbuck5** [comment] 2021-09-14 18:48
I don't think anyone here will debug 1600 lines of python where the problem is basically described as "it doesn't work."

Go to r/pygame, stackoverflow, or the pygame community discord - with a clear description of your problem, with screenshots of the problem, and with a link to your code, and someone can probably help you out.

**Comment by RickyAsbury** [comment] 2021-09-15 02:45
I never said it doesn't work I just didn't know what was causing the glitch it is located in class Goku def update, if self.charge==True
In the sprites.py and accessed if the player chooses goku on AOR.py and presses up and z at the same time like I said before I don't know if it's pygame or my computer

**Comment by ankith26** [comment] 2021-09-15 03:03
Well, as already pointed above, github issues are for issues pertaining to pygame itself. If your code has issues and you need help debugging, ask elsewhere, do not open github issues. If the bug in your game is a bug in pygame itself and you are sure of it and you can also prove it by a "simple reproducer", a bit of code that is ideally a few lines in size, and clearly demonstrates the issue, feel free to open another issue!
