### ISSUE TITLE
metadata-generation-failed

### ISSUE THREAD

**Issue by Skribbles64** [pygame/pygame#3645] opened 2022-12-29 19:33 UTC
- Windows 10
- Python 3.11.0

 when 'pip install pygame is run', this outputs:

Defaulting to user installation because normal site-packages is not writeable
Collecting pygame
  Using cached pygame-2.1.2.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
     
     
      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...
     
      Traceback (most recent call last):
        File "C:\Program Files\Python311\Lib\urllib\request.py", line 1348, in do_open
          h.request(req.get_method(), req.selector, req.data, headers,
        File "C:\Program Files\Python311\Lib\http\client.py", line 1282, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "C:\Program Files\Python311\Lib\http\client.py", line 1328, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "C:\Program Files\Python311\Lib\http\client.py", line 1277, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "C:\Program Files\Python311\Lib\http\client.py", line 1037, in _send_output
          self.send(msg)
        File "C:\Program Files\Python311\Lib\http\client.py", line 975, in send
          self.connect()
        File "C:\Program Files\Python311\Lib\http\client.py", line 1454, in connect
          self.sock = self._context.wrap_socket(self.sock,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\ssl.py", line 517, in wrap_socket
          return self.sslsocket_class._create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\ssl.py", line 1075, in _create
          self.do_handshake()
        File "C:\Program Files\Python311\Lib\ssl.py", line 1346, in do_handshake
          self._sslobj.do_handshake()
      ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:992)
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Frankiechrissarahole\AppData\Local\Temp\pip-install-rf5dgtkb\pygame_020c04b4aa8440f29bb804191766cbb6\setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\Frankiechrissarahole\AppData\Local\Temp\pip-install-rf5dgtkb\pygame_020c04b4aa8440f29bb804191766cbb6\buildconfig\config.py", line 225, in main
          deps = CFG.main(**kwds)
                 ^^^^^^^^^^^^^^^^
        File "C:\Users\Frankiechrissarahole\AppData\Local\Temp\pip-install-rf5dgtkb\pygame_020c04b4aa8440f29bb804191766cbb6\buildconfig\config_win.py", line 497, in main
          and download_win_prebuilt.ask(**download_kwargs):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Frankiechrissarahole\AppData\Local\Temp\pip-install-rf5dgtkb\pygame_020c04b4aa8440f29bb804191766cbb6\buildconfig\download_win_prebuilt.py", line 290, in ask
          update(x86=x86, x64=x64)
        File "C:\Users\Frankiechrissarahole\AppData\Local\Temp\pip-install-rf5dgtkb\pygame_020c04b4aa8440f29bb804191766cbb6\buildconfig\download_win_prebuilt.py", line 273, in update
          download_prebuilts(download_dir, x86=x86, x64=x64)
        File "C:\Users\Frankiechrissarahole\AppData\Local\Temp\pip-install-rf5dgtkb\pygame_020c04b4aa8440f29bb804191766cbb6\buildconfig\download_win_prebuilt.py", line 124, in download_prebuilts
          download_sha1_unzip(url, checksum, temp_dir, 1)
        File "C:\Users\Frankiechrissarahole\AppData\Local\Temp\pip-install-rf5dgtkb\pygame_020c04b4aa8440f29bb804191766cbb6\buildconfig\download_win_prebuilt.py", line 54, in download_sha1_unzip
          response = urllib.urlopen(request).read()
                     ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\urllib\request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\urllib\request.py", line 519, in open
          response = self._open(req, data)
                     ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\urllib\request.py", line 536, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\urllib\request.py", line 496, in _call_chain
          result = func(*args)
                   ^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\urllib\request.py", line 1391, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python311\Lib\urllib\request.py", line 1351, in do_open
          raise URLError(err)
      urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:992)>
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip ed561079ec622b0bab5a9e02976f5d540b0622da
     
      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by oddbookworm** [comment] 2022-12-29 21:08
`pip install pygame —pre`

**Comment by oddbookworm** [comment] 2022-12-30 04:08
@Skribbles64 did that solve your problem?

**Comment by Starbuck5** [comment] 2022-12-30 05:22
Thanks for reporting. This is a duplicate of #3522, so I'm going to close this issue to keep the tracker clear.

**Closed by Starbuck5** 2022-12-30 05:22 UTC
Labels: bug

**Comment by Skribbles64** [comment] 2022-12-31 16:16
> @Skribbles64 did that solve your problem?

Yes, thank you.
