### ISSUE TITLE
display.set_mode() Flag 'SCALED' behaves differently in pygame 2.0.0.dev8 and pygame 2.0.0.dev10

### ISSUE THREAD

**Issue by Just-JC** [pygame/pygame#1902] opened 2020-06-02 20:19 UTC
When pygame 2.0.0.dev10 was released on May 31st, I had previously been using version 2.0.0.dev8 with display surfaces using the 'SCALED' and 'RESIZABLE' flags on Windows 10, on a 1080p monitor.

I then installed the 2.0.0.dev10 release and while working on a simple scene, the display surface using the 'SCALED' flag worked as expected, but when I added the 'RESIZABLE' flag, the display surface showed a visible black border around it, unlike in the dev8 release, where the display window was completely filled out.

**Initial display window (854, 480) with 'RESIZABLE | SCALED' on 2.0.0.dev8 and dev10:**
![Screenshot (58)](https://user-images.githubusercontent.com/65417594/83562879-983ba580-a51a-11ea-9539-3ae8e4e99814.png)

**Maximized window (854, 480) on pygame 2.0.0.dev8:**
![Screenshot (56)](https://user-images.githubusercontent.com/65417594/83562547-092e8d80-a51a-11ea-83e1-7d7e8d23f89e.png)

**Maximized window (854, 480) on pygame 2.0.0.dev10:**
![Screenshot (55)](https://user-images.githubusercontent.com/65417594/83562462-e9976500-a519-11ea-8127-eeee0702810f.png)

**Initial display window (960, 540) with 'RESIZABLE | SCALED' on 2.0.0.dev8 and dev10:**
![Screenshot (60)](https://user-images.githubusercontent.com/65417594/83565425-b2778280-a51e-11ea-84e1-fd0bc4c212fc.png)

**Maximized window (960, 540) on pygame 2.0.0.dev8:**
![Screenshot (61)](https://user-images.githubusercontent.com/65417594/83565502-d0dd7e00-a51e-11ea-8308-7e80d6b8e1bb.png)

**Maximized window (960, 540) on pygame 2.0.0.dev10:**
![Screenshot (59)](https://user-images.githubusercontent.com/65417594/83565095-12b9f480-a51e-11ea-904b-1d9c1653bede.png)

Is this the final intended behaviour for the 'SCALED' display flag?

There are some scenarios where the behaviour in dev8 could be preferable, since the scaled-up pygame window in maximized view prevents requiring too large resolutions for display.set_mode().

Maybe there should be an option in display.set_mode() to switch between these two behaviours?

**Comment by MyreMylar** [comment] 2020-06-03 08:39
The behaviour of SCALED has changed

**Comment by illume** [comment] 2020-06-03 14:52
Yeah, SCALED needs to be specified and tested.

**Comment by robertpfeiffer** [comment] 2020-06-04 09:17
This will hopefully be fixed by #1897.

This one in particular is intended behaviour for resizing, but not for maximising. https://user-images.githubusercontent.com/65417594/83562462-e9976500-a519-11ea-8127-eeee0702810f.png

If a window is resized, we try to stick to an upscaling integer ratio. If the window is maximised or FULLSCREEN, this constraint is supposed to be relaxed, to make use of the whole screen even if some pixels are bigger than others.

**Comment by robertpfeiffer** [comment] 2020-10-11 09:05
This should have been fixed in 2.0.0-dev12. Maximised windows now use the available space similar to FULLSCREEN, resizing keeps crisp integer scaling ratio.

**Closed by robertpfeiffer** 2020-10-11 09:05 UTC
Labels: display
