### ISSUE TITLE
Add function to try & set window position display.set_window_pos(x, y)

### ISSUE THREAD

**Issue by Erdogan-0** [pygame/pygame#1890] opened 2020-06-01 17:20 UTC
The following code sets the window position to the center of the screen and then sets it to the upper left corner. This code works in pygame 1.9.6 but fails in pygame 2.0.0dev10 + Windows 10. Specifically, 2.0.0dev10 recognizes the first change to the window position but not the second.
```
import pygame
import os


def main():
    pygame.init()
    
    WINDOW_SIZE = (100, 100)

    monitor = pygame.math.Vector2(pygame.display.Info().current_w, pygame.display.Info().current_h)
    window_position = ((monitor.x - WINDOW_SIZE[0]) / 2, (monitor.y - WINDOW_SIZE[1]) / 2)
    
    #Set it the first time - works.
    os.environ['SDL_VIDEO_WINDOW_POS'] = "%d,%d" % window_position
    screen = pygame.display.set_mode(WINDOW_SIZE, pygame.NOFRAME)

    #Set it the second time - does nothing?
    os.environ['SDL_VIDEO_WINDOW_POS'] = "%d,%d" % (0, 0) 
    WINDOW_SIZE = (WINDOW_SIZE[0] + 1, WINDOW_SIZE[1]) if WINDOW_SIZE[0] % 2 == 0 else (WINDOW_SIZE[0] - 1, WINDOW_SIZE[1]) #Hack that makes sure the window is moved on Windows
    screen = pygame.display.set_mode(WINDOW_SIZE, pygame.NOFRAME)

    running = True
    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
                break
        
        screen.fill((0, 0, 255))

        pygame.display.update()

if __name__ == "__main__":
    main()
```
**Edit:** As @robertpfeiffer points out below, this behavior is intended and correct. However, this leaves the current version of Pygame without a way to change the window position multiple times. I propose adding a `set_window_pos` to the display module, which would not only alleviate this deficiency, but also make it more clearer to new Pygame users how to change the window position.

**Comment by MyreMylar** [comment] 2020-06-01 17:29
I think that there are several things broken whenever set_mode() is called twice. Luckily it has become less necessary now with `display.toggle_fullscreen()` and the new way window resizing works. 

Perhaps we also need a function that sets the size of an already created display and then maybe we can abandon all need to call set_mode() multiple time in a program.

**Comment by MyreMylar** [comment] 2020-06-01 17:43
Similar issue with multiple calls to set_mode() here: https://github.com/pygame/pygame/issues/212

**Comment by robertpfeiffer** [comment] 2020-06-02 11:10
This is by design. Consider this use case:
```
$ SDL_VIDEO_WINDOW_POS=blah python3 my_game.py
```
The first call to set_mode creates a new window.
```
screen=pygame.display.set_mode((640, 480))
```

The user moves the window around, and now it's at a different place. Then the user resizes the window. Should the already created and manually moved window jump back to the place specified in the environment variable? I don't think so.

I propose we close this as won't fix. We can expose this kind of functionality as an additional explicit parameter to set_mode if we really must, but the handling of the environment variable should stay the way it is, or it will break existing games.

**Comment by Erdogan-0** [comment] 2020-06-02 18:32
I agree with most of those points but I don't think the issue should be closed, as, even though the current behavior is intentional, there is no way (that I know of) to change the window position again. I propose adding a set window position function or something similar using `set_mode` parameters as @robertpfeiffer suggested. Additionally, it may be a good idea to change the label for this issue from _bug_ to _enhancement_ and the title to something like _Add window repositioning support_.

**Comment by MightyJosip** [comment] 2020-06-03 12:40
More discussion here: https://github.com/pygame/pygame/pull/1500

**Comment by illume** [comment] 2020-06-03 19:05
video.Window.position can set the position. It's an experimental API, and may change.

```python
import pygame
from pygame._sdl2.video import Window
...
pygame.display.set_mode(...)
window = Window.from_display_module()
window.position = (2, 2)
```

**Closed by illume** 2020-06-03 19:05 UTC
Labels: C code, Difficulty: moderate, SDL2, display, enhancement

**Comment by Freds-Turn** [comment] 2023-01-21 15:22
> video.Window.position can set the position. It's an experimental API, and may change.
> 
> ```python
> import pygame
> from pygame._sdl2.video import Window
> ...
> pygame.display.set_mode(...)
> window = Window.from_display_module()
> window.position = (2, 2)
> ```

fyi: I tried this in 2.1.2 and got the following error:
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault

**Comment by oddbookworm** [comment] 2023-01-21 15:25
@Freds-Turn try the most recent prerelease (`pip install pygame --pre --upgrade`). The following code works perfectly fine for me on current `main`

```
import pygame
from pygame._sdl2.video import Window

pygame.display.set_mode((500, 500))
window = Window.from_display_module()
window.position = (2, 2)

print("test")
```

**Comment by Freds-Turn** [comment] 2023-01-21 22:10
> pygame.display.set_mode((500, 500))
> window = Window.from_display_module()
> window.position = (2, 2)
> 
> print("test")
@oddbookworm 
Thank you, but it turns out that I was causing a side effect by sending the Window class outside of the scope instead of the window object and that is what was killing it, not the version.  I will share my stupidity in case someone else stumbles upon this thread with the same issue as me.  Here is a simple example of what not to do:

```python
import pygame as pg
from pygame._sdl2.video import Window

def move(Win):
    window = Win.from_display_module()
    window.position = (0, 32)

clock = pg.time.Clock()
pg.display.set_mode((500, 500))

while True:
    clock.tick(20)
    for event in pg.event.get():
        if event.type == pg.KEYDOWN:
            if event.key == pg.K_t:
                move(Window)
                # this works:
                # window = Window.from_display_module()
                # window.position = (0, 32)
                # this also works:
                # window = Window.from_display_module()
                # move(window)
                # but sending the class outside the scope does not work, in my case it was outside the module.
```

**Comment by oddbookworm** [comment] 2023-01-21 23:02
Actually, it all segfaults for me, but I can't seem to get a consistent gdb output as to where it's segfaulting. It will eventually segfault if you press "T" enough

**Comment by oddbookworm** [comment] 2023-01-21 23:05
```
import pygame as pg
from pygame._sdl2.video import Window

window = None

def move(Win):
    global window
    window = Win.from_display_module()
    window.position = (0, 32)

clock = pg.time.Clock()
pg.display.set_mode((500, 500))

while True:
    for event in pg.event.get():
        if event.type == pg.KEYDOWN:
            if event.key == pg.K_t:
                move(Window)
```
This doesn't seem to segfault for me though
