### ISSUE TITLE
surface blits destination rects can't be over 16bits

### ISSUE THREAD

**Issue by galexandreg** [pygame/pygame#1876] opened 2020-05-29 20:43 UTC
This is related to #1868 and #1869. It's not a "real" issue, and it's probably in the SDL. But since I changed stuff related to this, I thought I would share it in case I made a mistake somewhere. I am new to all this and self learning...  I don't trust myself too much I guess 😕 .

### Problem
I realized that while my pull request changed the behaviour of the area and dest arguments of Surface.Blit, I only tested the y value of area.

So I tested the other stuff and discovered that **I still can't use big values as a destination rect**.

### Test1
This will test using >16bit ints as area rects (x, y, w and h) and destination (x, y)
It prints OK after a successful test.
BIG DESTINATION X and Y are not working.
```
import pygame

pygame.init()

src1 = pygame.Surface((65536, 1))
src2 = pygame.Surface((1, 65536))
src1.fill((0, 255, 0))
src2.fill((0, 255, 0))
    
dst1 = pygame.Surface((2, 1))
dst2 = pygame.Surface((65537, 1))
dst3 = pygame.Surface((1, 65537))
dst1.fill((255, 0, 0))
dst2.fill((255, 0, 0))
dst3.fill((255, 0, 0))

dst1.blit(src1, (0, 0), area=(32768, 0, 1, 1))
dst1.blit(src2, (1, 0), area=(0, 32768, 1, 1))

dst2.blit(src1, (0, 0), area=(0, 0, 65536, 1))
dst3.blit(src2, (0, 0), area=(0, 0, 1, 65536))
    
dst2.blit(src1, (65536, 1), area=(0, 0, 1, 1))
dst3.blit(src1, (1, 65536), area=(0, 0, 1, 1))

print("BIG AREA X: ")
if dst1.get_at((0, 0)) == (0, 255, 0, 255):
    print("OK")

print("BIG AREA Y:")
if dst1.get_at((1, 0)) == (0, 255, 0, 255):
    print("OK")

print("BIG AREA W:")    
if dst2.get_at((65535, 0)) == (0, 255, 0, 255):
    print("OK")

print("BIG AREA H:")
if dst3.get_at((0, 65535)) == (0, 255, 0, 255):
    print("OK")

print("BIG DESTINATION X:")    
if dst2.get_at((65536, 0)) == (0, 255, 0, 255):
    print("OK")

print("BIG DESTINATION Y:")
if dst3.get_at((0, 65536)) == (0, 255, 0, 255):
    print("OK")
```

### Test2
**It looks like using a destination x and y bigger than 65535 will overflow.** If I try to blit a green pixel to (65536, 0), it blits to (0, 0). (65537, 0) to (1, 0) ...

**This was normal when blit was casting the rect values to 16bit... but I removed it for SDL2**
```
import pygame

pygame.init()
print()

src = pygame.Surface((1, 1))
src.fill((0, 255, 0))
dst = pygame.Surface((128000, 1))
dst.fill((255, 0, 0))

print("Destination 0,0:");
print(dst.get_at((0, 0)))
print("Destination 65536,0:");
print(dst.get_at((65536, 0)))
print()

print("blit 1x1 green pixel to dst (65536, 0)")
dst.blit(src, (65536, 0))
print()

print("Destination 0,0:");
print(dst.get_at((0, 0)))
print("Destination 65536,0:");
print(dst.get_at((65536, 0)))
```

I can use surface set_at() and get_at() fine with big numbers.
```
import pygame

pygame.init()

surf = pygame.Surface((128000, 1))
surf.fill((0, 255, 0))

print(surf.get_at((65536, 0)))
print(surf.get_at((0, 0)))
surf.set_at((65536, 0), (0, 0, 0))
print(surf.get_at((65536, 0)))
print(surf.get_at((0, 0)))
```
Changing (65536, 0) with set_at() will change 65536, not 0. **So there is no problem in surfaces, rects or get_at...**

### Conclusion

Rects, surfaces, blit areas, get_at, set_at... all work with bigger numbers, but destination rects still overflow

This is probably in the SDL, not pygame. The full "new" normal int rect is not modified anywhere in Pygame until it goes to SDL_BlitSurface. **I also tried it manually with a test SDL program and it does the same thing, even if surfaces and rects both support > 16 bit numbers.**

All this is not really useful... While I guess it's possible someone will want to blit a small portion of a really big surface (> uint16), blitting to a surface bigger than 65535 pixels seems improbable. It also seems to be somewhere in the SDL, so there is no way to "fix" it here.

Anyway... I simply wanted to share it, in case I did something wrong in my pr.

**Comment by illume** [comment] 2020-05-30 07:15
Thanks for the report and the tests. I changed your area test into a unit test here: https://github.com/pygame/pygame/pull/1875

**Comment by galexandreg** [comment] 2020-05-30 16:36
> Thanks for the report and the tests. I changed your area test into a unit test here: #1875

Thank you 😄 

This was more about the fact that even without the 16bit casting, and with rects, surfaces and other stuff working with bigger numbers, **blitting to a destination bigger than 16bit still doesn't work**, even if it seems like it should.

**But if you agree with my conclusion that it seems to be caused by the SDL, and you still don't see any problems with my original PR, I'm happy with it.** After all, blitting to such a huge surface is not very useful...

I guess this is more a combination of being a beginner and lacking self confidence... 😕 
I simply don't want to cause a problem because prople trusted what I did too much.

Thanks 😄

**Comment by MyreMylar** [comment] 2020-05-31 13:37
Poking around in the SDL blitting it looks like the data from the destination rectangle is eventually cast to Uint16s in various blits. For example here:

https://github.com/spurious/SDL-mirror/blob/3e7e51f2db6f1bac998afd533ed9849c192c46e4/src/video/SDL_blit.c#L77

Where the positions are cast to Uint16

**Comment by MyreMylar** [comment] 2020-05-31 13:40
If that does work without causing chaos it seems like it would be an easy patch to SDL.

**Comment by galexandreg** [comment] 2020-05-31 17:10
I'm not sure that i'm comfortable enough yet to patch the SDL itself. If they do it like this, it must be useful for something...

It's not like it's a big issue either. Selecting an area bigger than a signed int16 might be useful (#1869), but a destination bigger than a unsigned int 16 seems unlikely.

The goal of my pr was to make SDL and Pygame blits work the same way, and they do now.
At this point, it's not a "bug", it's not in Pygame, and I bet that it will never be useful... If everyone is happy about my original pr, I guess this issue could be closed.

Feel free to do what you think is best 😄 
Thanks!

**Comment by galexandreg** [comment] 2020-05-31 20:32
I feel like I might have gone a bit over my actual programming skills... heh... that's how you learn I guess.

I am sorry if I took some of your time with what is a big learning experience for me. Here are the things I tested and my questions. **If you think it makes sense, I will try and stop thinking about it 😕   The issue could also probably be closed. This is not an "issue", and probably will never be a problem for anyone. It's your choice.**

It seems the tests I did were not very good and missed some stuff.

In the last PR, I stopped casting internal pygame rects before giving them to SDL. In SDL2, pygame GAME_Rects and SDL_Rects are the same, so there is no need to cast them to 16bit anymore. I think this makes sense? Does it? Even with all this?

I thought it would allow everything to work with normal ints (after all, rects and surfaces do)

It turns out, it doesn't. Stuff will still overflow somewhere in the SDL when blitting.

My observations (probably not perfect...):
**Area x-y:** With my patch, it doesn't overflow at signed 16bit anymore, but it does at unsigned 16bit.
**Area w-h:** Looks like it doesn't overflow at 16 bit at all.
**Destination:** Overflow at 65536.

So, as I said, I think I got myself in something a little over my programming skills. I'm really sorry again if I used your time for nothing.

Thanks

**Comment by MyreMylar** [comment] 2020-06-04 19:20
Yeah I think we can probably close this. If anybody ever coems up with a use case for needing huge destination rects then I guess we'll point them towards SDL first.

**Closed by MyreMylar** 2020-06-04 19:20 UTC
Labels: C code, Difficulty: Easy, SDL, SDL2, Surface

**Comment by galexandreg** [comment] 2020-06-27 17:29
It turns out I looked at it a little too fast, and it's not only in the SDL. Pygame also has its own blitting function for some image formats (pygame_Blit, SoftBlitPyGame) that also do this. I think it doesn't change anything really, and it's still not worth looking at, but I felt like adding the information to the issue in case someone reads it in the future.

**Comment by browarsoftware** [comment] 2026-01-22 11:29
I have a case caused by this limitation. I have a single texture that holds sprites of animations of several in-game characters in resolution 256x256. I use this texture inside the OpenGL vertex shader by accessing it with sampler2DArray and texture() function. The input texture was prepared using blit. When pixel indexes in blit were greater than 2 bytes, the overflow happened, and blit started again from 0. I have overcome it by making the layout of reference texture not a column-style but a grid style, and rewriting the vertex shader. But yes, this issue might happen when you write a real-sized game, not a toy example. :-)

BTW – great job with Pygame! For some projects, even 3D, it is far better than Unity or Godot.
