### ISSUE TITLE
SDL2: pygame.event.post() does not post some event types

### ISSUE THREAD

**Issue by charlesej** [pygame/pygame#1238] opened 2019-08-10 18:46 UTC
The following code shows that some event types are not appearing in the event queue after being posted using `pygame.event.post()`. Running the code and pressing 'q' creates and posts 2 different event types (`KEYDOWN` and `USEREVENT`).
- Using pygame 1.9.4, both events appear in the event queue after being posted.
- Using pygame 2.0.0.dev3, the `USEREVENT` event is posted and appears in the event queue, but the `KEYDOWN` event does not appear in the event queue when posted.

Note: Uncovered this issue while investigating #1236.

---

```python
import pygame


def add_event(event_type):
    new_event = pygame.event.Event(event_type, unicode='a', key=ord('a'))
    print('Adding event:', new_event)
    pygame.event.post(new_event)
    print('Peeking:', pygame.event.peek(event_type))


pygame.init()

screen = pygame.display.set_mode((400, 200))
pygame.display.flip()
clock = pygame.time.Clock()
running = True

while running:
    clock.tick(20)

    for e in pygame.event.get():
        if e.type == pygame.QUIT:
            running = False
        elif e.type == pygame.KEYDOWN:
            print('Handling event:', e)

            if e.key == pygame.K_ESCAPE:
                running = False
            elif e.key == pygame.K_q:
                # Pressing 'q' adds KEYDOWN and USEREVENT events.
                add_event(pygame.KEYDOWN)
                add_event(pygame.USEREVENT)
        elif e.type == pygame.USEREVENT:
            print('Handling event:', e)

pygame.quit()
```

---

Output using pygame 1.9.4. Both events appear in the event queue after being posted.
```
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Handling event: <Event(2-KeyDown {'unicode': 'q', 'key': 113, 'mod': 0, 'scancode': 16})>
Adding event: <Event(2-KeyDown {'unicode': 'a', 'key': 97})>
Peeking: 1
Adding event: <Event(24-UserEvent {'unicode': 'a', 'key': 97})>
Peeking: 1
Handling event: <Event(2-KeyDown {'unicode': 'a', 'key': 97})>
Handling event: <Event(24-UserEvent {'unicode': 'a', 'key': 97})>
```

---

Output using pygame 2.0.0.dev3 at 7a5ed0b864645e7c325d80aa8866e837559c7a1c. The `USEREVENT` event appears in the event queue after being posted, but the `KEYDOWN` event does not.
```
pygame 2.0.0.dev3 (SDL 2.0.10, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
Handling event: <Event(768-KeyDown {'unicode': 'q', 'key': 113, 'mod': 4096, 'scancode': 20, 'window': None})>
Adding event: <Event(768-KeyDown {'unicode': 'a', 'key': 97})>
Peeking: 0
Adding event: <Event(32768-UserEvent {'unicode': 'a', 'key': 97})>
Peeking: 1
Handling event: <Event(32768-UserEvent {'unicode': 'a', 'key': 97})>
```

---

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit) and 2.7.10 (64bit)
- pygame: 2.0.0.dev3 (SDL: 2.0.10) at 7a5ed0b864645e7c325d80aa8866e837559c7a1c

**Related Docs:** https://www.pygame.org/docs/ref/event.html#pygame.event.post

**Comment by robertpfeiffer** [comment] 2020-04-07 12:21
I figured out why this bug resists unit testing! Look at this test case:
```python
import pygame
for i in range(2):
    pygame.display.init()
    pygame.event.clear()

    new_event = pygame.event.Event(pygame.KEYDOWN, key=pygame.K_a)
    pygame.event.post(new_event)
    print(new_event)
    print(pygame.event.poll())
    print("--")
    
    pygame.display.quit()
```
output: 
```
pygame 2.0.0.dev6 (SDL 2.0.10, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
<Event(768-KeyDown {'key': 97})>
<Event(0-NoEvent {})>
--
<Event(768-KeyDown {'key': 97})>
<Event(768-KeyDown {'key': 97})>
--
```

and this:
```python
import pygame
pygame.init()
for i in range(2):
    pygame.display.init()
    pygame.event.clear()

    new_event = pygame.event.Event(pygame.KEYDOWN, key=pygame.K_a)
    pygame.event.post(new_event)
    print(new_event)
    print(pygame.event.poll())
    print("--")
    
    pygame.display.quit()
```
output:
```
pygame 2.0.0.dev6 (SDL 2.0.10, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
<Event(768-KeyDown {'key': 97})>
<Event(0-NoEvent {})>
--
<Event(768-KeyDown {'key': 97})>
<Event(0-NoEvent {})>
--
```

**Comment by ankith26** [comment] 2020-10-24 10:58
#2244 mostly fixes this issue

**Comment by illume** [comment] 2020-10-25 11:29
Here is the result python3 Mac with #2244 merged in. Seems ok to me.
```python
Handling event: <Event(768-KeyDown {'unicode': 'q', 'key': 113, 'mod': 0, 'scancode': 20, 'window': None})>
Adding event: <Event(768-KeyDown {'unicode': 'a', 'key': 97})>
Peeking: 1
Adding event: <Event(32774-UserEvent {'unicode': 'a', 'key': 97})>
Peeking: 1
Handling event: <Event(768-KeyDown {'unicode': '', 'key': 97, 'mod': 2544, 'scancode': 199497328, 'window': None})>
Handling event: <Event(32774-UserEvent {'unicode': 'a', 'key': 97})>
```

**Comment by illume** [comment] 2020-10-25 11:39
Thanks @ankith26 it does seem fixed now.

**Comment by ankith26** [comment] 2020-12-17 17:24
Well this issue has been fixed. The only reason this is open was to make sure the unicode attribute could be posted on KEYDOWN events.
That’s all working now

**Comment by illume** [comment] 2020-12-17 17:28
This PR fixes this issue for me: https://github.com/pygame/pygame/pull/2398
`ankith26-event-get`

To reproduce run the example in the first post of this issue, and press q key.  Note the 'unicode': should be 'unicode': 'a'.

**Comment by illume** [comment] 2020-12-17 17:55
Since #2398 fixes this, I'll close it. Thanks!

**Closed by illume** 2020-12-17 17:55 UTC
Labels: C code, Compatability (Pygame 2), Difficulty: Easy, SDL2, critical, event, needs-investigation
