### ISSUE TITLE
Test failures (test_SRCALPHA, test_pixel_alpha, test_subsurface) on 32-bit ARM

### ISSUE THREAD

**Issue by thesamesam** [pygame/pygame#1933] opened 2020-06-08 18:38 UTC
Hi there,

I'm a Gentoo user who's encountered some ARM test failures while we've been testing out newer versions of Pygame for the distribution. Please let me know what further information I can provide.

```
======================================================================
FAIL: test_SRCALPHA (pygame.tests.blit_test.BlitTest)
SRCALPHA tests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_7/test/lib/pygame-2.0.0.dev11-py3.7-linux-armv7l.egg/pygame/tests/blit_test.py", line 19, in test_SRCALPHA
    self.assertEqual(s.get_at((0, 0)), d.get_at((0, 0)))
AssertionError: (0, 0, 255, 0) != (0, 0, 255, 255)

======================================================================
FAIL: test_pixel_alpha (pygame.tests.surface_test.SurfaceSelfBlitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_7/test/lib/pygame-2.0.0.dev11-py3.7-linux-armv7l.egg/pygame/tests/surface_test.py", line 3040, in test_pixel_alpha
    self._assert_same(surf, comp)
  File "/var/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_7/test/lib/pygame-2.0.0.dev11-py3.7-linux-armv7l.egg/pygame/tests/surface_test.py", line 2951, in _assert_same
    % (a.get_at((x, y)), b.get_at((x, y)), a.get_bitsize())
AssertionError: (0, 255, 0, 255) != (0, 255, 0, 0) : (0, 255, 0, 255) != (0, 255, 0, 0), bpp: 32

======================================================================
FAIL: test_subsurface (pygame.tests.surface_test.SurfaceSelfBlitTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_7/test/lib/pygame-2.0.0.dev11-py3.7-linux-armv7l.egg/pygame/tests/surface_test.py", line 3082, in test_subsurface
    self._assert_same(surf, comp)
  File "/var/tmp/portage/dev-python/pygame-9999/work/pygame-9999-python3_7/test/lib/pygame-2.0.0.dev11-py3.7-linux-armv7l.egg/pygame/tests/surface_test.py", line 2951, in _assert_same
    % (a.get_at((x, y)), b.get_at((x, y)), a.get_bitsize())
AssertionError: (0, 255, 0, 255) != (0, 255, 0, 0) : (0, 255, 0, 255) != (0, 255, 0, 0), bpp: 32

----------------------------------------------------------------------
Ran 1505 tests in 206.636s

FAILED (failures=3)
```

I've attached the full [build.txt](https://github.com/pygame/pygame/files/4747907/build.txt) in case this helps. I've done this all on a headless machine, inside of a chroot.

[System information](https://github.com/pygame/pygame/files/4747933/sysinfo.txt)

**Comment by MyreMylar** [comment] 2020-06-08 18:59
There are some SDL arm bugs that may be relevant here, see my last comment here:
https://bugzilla.libsdl.org/show_bug.cgi?id=4365

for more details but essentially it looks like alpha is broken on Arm unless you compile SDL with the simd optimisations disabled. Not sure how comfortable you are with rebuilding SDL from source but the instructions here are pretty good:

https://wiki.libsdl.org/Installation

Essentially to build it with SIMD optimisations disabled you want:

    hg clone https://hg.libsdl.org/SDL SDL
    cd SDL
    mkdir build
    cd build
    ../configure --disable-arm-simd
    make
    sudo make install

I'd love to know if that fixes the test failures you are seeing.

**Comment by thesamesam** [comment] 2020-06-08 20:09
Thanks for your quick response! All tests pass with ```--disable-arm-simd```.

**Comment by MyreMylar** [comment] 2020-06-08 20:21
> Thanks for your quick response! All tests pass with `--disable-arm-simd` on libsdl2. Does a new bug need to be filed upstream?

Not sure, I'm not as familiar with the ins and outs of the SDL community. Perhaps you could add a comment in this existing thread mentioning that you encountered the same problems in another environment/platform? I think if more people are having the same problem it is more likely to attract attention.

The code itself with the problem is all written in assembly as far as I can tell which I have no idea how to fix.

**Comment by MyreMylar** [comment] 2020-07-02 14:26
Looks like these will be arm-simd things will be disabled in version 2.0.13 of SDL when that turns up, so we should retest this then. I'll tag this.

**Comment by ankith26** [comment] 2021-01-22 15:20
SDL 2.0.14 has already released, and those arm optimizations are disabled by default. So this issue is fixed, hence closing.
Feel free to reopen, if the issue still somehow persists

**Closed by ankith26** 2021-01-22 15:20 UTC
Labels: Arm, Difficulty: Waiting, SDL 2.0.14, SDL2, bug, raspi
