### ISSUE TITLE
Pygame not detecting duplicate keyboard input events

### ISSUE THREAD

**Issue by Tollund** [pygame/pygame#3670] opened 2023-01-13 12:13 UTC
**Environment:**

- **Operating system** : Raspberry Pi OS
- **Python version** : 3.9.2
- **SDL version** : 2.0.14
- **PyGame version** : 2.1.2

**Current behavior:**

We're building a hardware device using a raspberry pi with a barcode scanner and a display. The barcode scanner functions like a USB keyboard, and sends keystrokes in quick succession after scanning a barcode. We're having a problem with pygame not detecting duplicate keys from the scanner in quick succession. When running the below code, pygame often misses duplicate keys. 

**Expected behavior:**

Pygame should detect all keyboard input correctly.

**Test Code**

```
import sys, pygame
pygame.init()
screen = pygame.display.set_mode((800, 400))
ID = ""
font = pygame.font.SysFont("Arial", 70)
while True:
        text = font.render("testtext", True, (255, 255, 255), (0, 0, 0))
        textRect = text.get_rect()
        textRect.center = (screen.get_width() // 2, screen.get_height() // 2)
        events = pygame.event.get()
        for event in events:
            if event.type == pygame.KEYDOWN:
                key = pygame.key.name(event.key)
                if key.isdigit():
                    ID += key
                elif key == "return":
                    print(ID)
                    ID = ""
                elif key == "left":
                    pygame.quit()
                    sys.exit()
        screen.fill((0, 0, 0))
        screen.blit(text, textRect)
        pygame.display.flip()
```

Output from scanning the same barcode using the above code:

```
5770857738
5770857738
570857738
577085738
57085738
5770857738
577085738
5770857738
5770857738
5770857738
5770857738
577085738
5770857738
570857738
5770857738
```

When I comment out the last three lines (not updating the screen), the barcode is scanned successfully every time.

**Comment by Tollund** [comment] 2023-01-13 12:16
From testing it looks like there is about 3-4 miliseconds between each keypress emitted by the scanner.

**Comment by illume** [comment] 2023-02-12 03:53
I guess it's probably not pygame related. It might be SDL related, but I don't know. 

Can you can reproduce it with other toolkits? This could at least let you narrow down the issue.

Probably there's not anything we can help with on the pygame side not having the hardware. If you _can not_ reproduce the problem with another toolkit (X11, or gtk, qt etc), then the next thing to investigate would be to see if you can reproduce with an SDL program.

If you haven't already, I'd add `print(event)` to confirm your logic is not at fault. Maybe you'll see it printing all the events after all.

Closing this, because the issue report is a month old and I guess you've moved on. Feel free to comment further if you think there's something to be done on the pygame side. Good luck!

**Closed by illume** 2023-02-12 03:53 UTC
Labels: bug
