### ISSUE TITLE
2.1.3.dev6 discussion

### ISSUE THREAD

**Issue by illume** [pygame/pygame#3408] opened 2022-08-20 07:22 UTC
Some things before 2.1.3...

- [x] I'm reviewing/editing/labelling from the bottom/newest (mostly).
- [x] I'd like we keep the SDL* lib versions the same on different platforms if we can. See https://github.com/pygame/pygame/pull/3042#issuecomment-1229426713 I added an issue for SDL 2.24.0 update here: https://github.com/pygame/pygame/issues/3430 since I think it's easier to update the manylinux scripts than revert the windows changes.
- [x] mark all new APIs as experimental in the docs? For a release or two until more people try them and perhaps uncover issues? [New API closed PRs](https://github.com/pygame/pygame/pulls?q=is%3Apr+is%3Aclosed+label%3A%22New+API%22)
- [x] Get settings path function in a context module needs a rethink: https://github.com/pygame/pygame/pull/3100 Will remove it before 2.3.dev6 is released. Also here: https://github.com/pygame/pygame/pull/3038
- [ ]  Fix issues with newbie guide changes: https://github.com/pygame/pygame/pull/3118  The parts about dirty rects being useless are incorrect.
- [x] there were some SDL_ functions defined, which breaks forwards compatibility. https://github.com/pygame/pygame/issues/3417 should be fixed before 2.1.3, but not the dev release.

Some things before 2.1.3.dev6...

**Comment by illume** [comment] 2022-08-20 09:14
Need to find out if this API change for math.clamp is acceptable: https://github.com/pygame/pygame/pull/3361 and if not, perhaps revert it.

**Comment by illume** [comment] 2022-08-20 09:23
Get settings path function in a context module needs a rethink: https://github.com/pygame/pygame/pull/3100 Will remove it before 2.3.dev6 is released.

**Comment by illume** [comment] 2022-08-20 09:31
Hrmm. With the module labels renamed to "Submodule: display" rather than "display" older links and queries are broken.
https://github.com/pygame/pygame/labels/display doesn't work for example.

The URLs are kind of weird now too:
- `https://github.com/pygame/pygame/labels/Submodule%3A%20display`
- `https://github.com/pygame/pygame/labels/display`

Probably they need to be renamed, and perhaps the description (rather than name) can stay as "Submodule: x".

**Comment by illume** [comment] 2022-08-20 09:39
This gcc specific error should probably block the release, because it breaks clang at least (and other compilers potentially). https://github.com/pygame/pygame/pull/3381

**Comment by illume** [comment] 2022-08-20 10:14
The "Awaiting merge" label is not necessary and biased. What it really means is, review required. If there's two reviews that are approved, then the PR is marked as approved.  If there's no review or one review, it marks it as 'review required'. Github marks it quite clearly I think. Otherwise it's marked as "review required". Saying it's ready to merge can perhaps mislead the next reviewer. For "I would like a review quickly" perhaps just the "needs review" label can be added. My 2c. I'd like to remove that label... unless I'm misunderstanding something.

**Comment by ankith26** [comment] 2022-08-20 10:28
On the topic of labels,

I had added the `Submodule: x` for organisation and better searchability of labels. I see its downs now, but I would still like to have a way to organise labels better. How about adopting a convention of `submodule-X`, that way it has a cleaner URL too

I'm fine with removing "Awaiting merge" (I had added it initially, and without much thought I admit), `needs-review` is accurate

**Comment by ankith26** [comment] 2022-08-20 10:45
There are no blockers for a dev release or a full release ATM... but there are a few nice-to-merge-before-a-release that I have in mind

#3317 is on the 2.1.3 label, and it's a fix for a regression from 2.1.2 that more than one person noticed

There's also #3396 which would make sense merging before a release, I'd prefer we not have `arg0` and `arg1` go out into the wilds (I missed this in a review :/). If you agree, you can add this to the milestone as well.

**Comment by illume** [comment] 2022-08-20 11:12
Yeah, I think the arg0, arg1 issue (https://github.com/pygame/pygame/pull/3396) is worth blocking a 2.1.3 release, but maybe not the dev release(It would be a nice to have for the dev release imho).

**Comment by illume** [comment] 2022-08-20 11:15
re: labels. started an issue here: https://github.com/pygame/pygame/issues/3413 not necessary to sort it before release.

**Comment by illume** [comment] 2022-08-20 11:56
There's a crash bug in this one: https://github.com/pygame/pygame/pull/3364 so may need reverting/fixing.

**Comment by Starbuck5** [comment] 2022-08-20 18:14
The awaiting merge label has helped our workflow a lot over the last 6 months or so, as we've been struggling to keep up on reviews. It's valuable to be able to see what's close to being approved to go be able to put those things over the top.

**Comment by illume** [comment] 2022-08-20 18:41
I still don't understand what it's good for. There's a text showing PRs that need review ("Review required"). 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/9541/185761706-6c1d452e-6b1d-41a2-966b-caadf23bca28.png">

I don't see how adding a label does anything except rush PR reviews. Which I don't think we ever need or want to rush them. When there are sufficient reviews the text changes to 'Approved'.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/9541/185761676-427c1197-b24d-4896-a603-e14d1ed50c7f.png">

**Comment by illume** [comment] 2022-08-20 19:41
Probably we should mark all new APIs as experimental in the docs? For a release or two until more people try them and perhaps uncover issues?

There was one new API here... https://github.com/pygame/pygame/pull/3396 but there are others in this release I guess. (following the New API tag).

**Comment by illume** [comment] 2022-08-20 19:47
I'm wondering if https://github.com/pygame/pygame/pull/3344 affects jedi/pylint/pylance etc.

**Comment by illume** [comment] 2022-08-20 19:52
- [ ] confirm if pygame (.tests/.examples.aliens) works on older macs https://github.com/pygame/pygame/pull/3347

**Comment by Starbuck5** [comment] 2022-08-20 19:57
Did you catch the description of the label?

Awaiting Merge:
>  For PRs that have at least one approving review and can be merged on subsequent reviews

For example, this PR by me:
![Capture](https://user-images.githubusercontent.com/46412508/185764030-4f9d75f5-2c22-4b73-8831-c2e1bffb01b1.PNG)

The awaiting merge tag tells other reviewers that somebody has already approved my PR, which is great, because it's a scary looking PR. Our key SIMD expert MyreMylar checked it off, in fact, which is great, because he's the only one I would expect to proactively look at a SIMD PR like this one. Other reviewers get the hint that this PR should be easy to approve, because it's already convinced one reviewer, so it helps prioritize limited reviewing capability to the PRs that are close to getting merged.

**Comment by Starbuck5** [comment] 2022-08-20 20:01
This is not a release blocker per se, but as far as I can @illume is the only person who can regenerate the linux dependency docker  images, which is why this is stalled: https://github.com/pygame/pygame/pull/3042

Good to get a little more up to date on dependencies for release. It's also blocking a lot of new API from new SDL_mixer, SDL_ttf versions.

**Comment by illume** [comment] 2022-08-20 20:17
Yeah, probably not a blocker for the dev release. But it'd be nice for 2.1.3. There's only me and two others who can upload the docker images(neither of which are active). Probably we can move this to github instead (because dockerhub now rate limits and charges), and allow more people access to do so. I'll see about giving Ankith access to our docker hub (if I have permission to do so) in the mean time.

- [ ] update deps in manylinux scripts needs updating and merging. https://github.com/pygame/pygame/pull/3042

Are the windows SDL_ deps updated?

**Comment by novialriptide** [comment] 2022-08-21 04:18
Could this be a potential release-blocker?
https://github.com/pygame/pygame/issues/3419

**Comment by Starbuck5** [comment] 2022-08-21 04:37
In my opinion it shouldn't block the release since it's not a regression, especially not the dev release. That being said it would be nice to get it fixed for the full release.

**Comment by illume** [comment] 2022-08-28 10:31
- [ ] I'd like we keep the SDL* lib versions the same on different platforms if we can. See https://github.com/pygame/pygame/pull/3042#issuecomment-1229426713

Personally I'm inclined that we update the linux/mac manylinux build scripts rather than drop windows versions down.

**Comment by illume** [comment] 2022-10-01 09:37
Tried to release a .dev6 last night but the docker images failed to build. 
After some hacking about, and many hours of waiting for builds to fail... they build.
Added glib and libffi as deps, for fluidsynth.
The end.

(pps. it's still building. Hopefully no more errors? We'll see in 30 minutes. My kingdom for an ARM VM. Oh, ARM VMs are available now on Azure... cool. But WHY NO ON GITHUB??!??! Anyway... set up VM, start compiling... the race is on!)
(ppps. oh, windows-arm is available on github actions in beta https://github.blog/changelog/2022-09-28-github-actions-self-hosted-runners-now-support-windows-arm-hardware/ they link here: https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-default-labels-to-route-jobs  maybe it already works with linux?)
(pppps. the new ARM VM won the build, even giving the emulator a significant head start. It's speeeeeedy.)

**Comment by ankith26** [comment] 2022-10-01 13:11
Ooh dev release, nice!

Went through pypi and noticed that the linux aarch64 wheels are accidently uploaded under the wrong tag (dev5) and manylinux2014 wheels seem to be missing too

**Closed** 2022-10-23 22:07 UTC
