### ISSUE TITLE
LayeredUpdates.get_sprites_at() always return empty list

### ISSUE THREAD

**Issue by anxuae** [pygame/pygame#1697] opened 2020-05-02 17:26 UTC
Rects with ``width=0`` and ``height=0`` are no more considered in ``collidelistall()``function:

```
>>> r0 = pygame.Rect(12, 102, 0, 0)
>>> r1 = pygame.Rect(10, 100, 40, 60)
```

pygame ``1.9.6``:
```
>>> print( r0.collidelistall([r1]) )
[0]
```

pygame ``2.0.0.dev6``:
```
>>> print( r0.collidelistall([r1]) )
[]
```

As results, the ``OrderedUpdates.get_sprites_at()`` method does not work anymore.
https://github.com/pygame/pygame/blob/45c996aa19357841f3ff57f3ca51c08abeef5894/src_py/sprite.py#L779-L791

**Comment by MightyJosip** [comment] 2020-05-02 17:34
Thank you for your report. This is side effect of the fix for #1197 made in PR #1226. As far as I know this was mostly semantics decision (because technically 0 sized rects doesn't exist/doesn't take any space). If you need the collision on one specific pixel use rect with width/height of 1. For now I will leave this open until we get more thoughts on this.

**Comment by nthykier** [comment] 2020-05-02 18:03
@MightyJosip As I read it, @anxuae is saying that we broke our own code (`get_spirtes_at` code referenced is from Pygame's own code base).  I.e. this is a regression.

**Comment by MightyJosip** [comment] 2020-05-02 19:18
@nthykier you are right I understood wrong his report. This should be fixed now. @anxuae thank you for your report.

**Closed** 2020-05-03 07:06 UTC
Labels: 2.0, sprite
