### ISSUE TITLE
Regression: Cannot post keydown events (or any non-USEREVENT events)

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#1580] opened 2020-02-17 07:26 UTC
This used to work with Pygame 1.9.6 (I tested it):

```python
import pygame
pygame.init()
screen=pygame.display.set_mode((50,50))
pygame.event.post(
            pygame.event.Event(pygame.KEYDOWN,
                           key=pygame.K_a))
pygame.event.get()
pygame.event.post(
        pygame.event.Event(pygame.KEYDOWN,
                           key=pygame.K_a,
                           unicode='',
                           mod=0,
                           scancode=4,
                           window=None))
pygame.event.get()
```

I.E. you could post arbitrary keydown events.

I relied on this behaviour in my tutorial here: https://blubberquark.tumblr.com/post/183424536830/pygame-and-asyncio-part-v-twitch-integration. TL;DR This tutorial explains how to interleave the `asyncio` event loop with a pygame game loop, so you can post `KEYDOWN` events from asyncio, so people can type commands in IRC and they show up in the game as key presses.

I tried to follow my own tutorial, and found out it doesn't work any more.

I looked at the code in event.c, and it seems to only create and populate USEREVENT structs, and fill their dicts with the supplied data. We probably need to check for known SDL event types and create the appropriate struct for SDL_KEYDOWN or whatever it's called instead. That is going to be a lot of code duplication if we do all known event types, but especially for KEY(DOWN|UP) events, it might be worth the effort to provide an easy way to retrofit touch controls onto existing games.

**Comment by charlesej** [comment] 2020-02-17 14:11
This sounds like a duplicate of issue #1238.

**Comment by robertpfeiffer** [comment] 2020-02-19 08:14
>This sounds like a duplicate of issue #1238.
Oh, it totally is!

As I said on Discord, I tracked the problem down in event.c:

https://github.com/pygame/pygame/blob/e07618a05545947f54c62d7b498f81059128f0ad/src_c/event.c#L1651
https://github.com/pygame/pygame/blob/e07618a05545947f54c62d7b498f81059128f0ad/src_c/event.c#L325
https://github.com/pygame/pygame/blob/e07618a05545947f54c62d7b498f81059128f0ad/src_c/event.c#L267

The SDL2 docs say:

> It is also possible to push events onto the event queue and so use it as a two-way communication path. Both SDL_PushEvent() and SDL_PeepEvents() allow you to place events onto the event queue. This is usually used to place a SDL_USEREVENT on the event queue, however you could use it to post fake input events if you wished. Creating your own events is a simple matter of choosing the event type you want, setting the type member and filling the appropriate member structure with information.

**Comment by illume** [comment] 2020-04-11 09:50
Closing because duplicate #1238.

**Closed by illume** 2020-04-11 09:50 UTC
Labels: 2.0, SDL2, bug, event
