### ISSUE TITLE
pygame2 does not generate MOUSEBUTTONUP events for mouse wheel

### ISSUE THREAD

**Issue by gummbum** [pygame/pygame#2240] opened 2020-10-23 22:10 UTC
**Environment:**

- **Operating system**: Windows 10
- **Python version**: 3.7.4
- **SDL version**: 2.0.12
- **PyGame version**: 2.0.0.dev22
- **Relevant hardware**: logitech wired optical mouse (basic model)

**Current behavior:**

Rolling the mouse wheel generates MOUSEBUTTONDOWN events, but no MOUSEBUTTONUP events. It does not matter if the mouse is moving or still.

**Expected behavior:**

The same behavior as pygame 1.9.6 is expected: it generates MOUSEBUTTONUP events.

**Screenshots**

NA

**Steps to reproduce:**

1. Run the provided code in pygame 1.9.6.
2. Scroll the mouse wheel up and down.
3. See the MOUSEBUTTONUP events are printed.
4. Run the provided code in pygame 2.0.0dev22 (or previous pygame2 version).
5. Scroll the mouse wheel up and down.
6. See the MOUSEBUTTONUP events are not printed.

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
import pygame
from pygame.locals import KEYDOWN, K_ESCAPE, QUIT, MOUSEBUTTONUP, MOUSEBUTTONDOWN
pygame.init()
clock = pygame.time.Clock()
screen = pygame.display.set_mode((400, 400))
while 1:
    clock.tick(30)
    for e in pygame.event.get():
        if e.type == KEYDOWN and e.key == K_ESCAPE:
                quit()
        elif e.type == QUIT:
            quit()
        elif e.type == MOUSEBUTTONDOWN:
            print('Mouse button down: {}'.format(e.button))
        elif e.type == MOUSEBUTTONUP:
            print('Mouse button up: {}'.format(e.button))
```

**Stack trace/error output/other error logs**

```
paste other relevent logs or stack traces here, if applicable
```

**Comment by siggisv** [comment] 2020-10-23 22:27
I can confirm that on Linux Mint 19.3, that test code in `pygame 2.0.0.dev14` behaves differently than when run in `pygame 1.9.6` (both installed with `pip install pygame== etc.`).

```
(venv-pygame-testing) siggisv@Lenoveau-S530:~/work/testing/pygame-testing$ python test.py 
pygame 2.0.0.dev14 (SDL 2.0.12, python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Mouse button down: 4
Mouse button down: 4
Mouse button down: 4
Mouse button down: 5
Mouse button down: 5
Mouse button down: 5
Mouse button down: 5
```

```
(venv-pygame.1.9.6) siggisv@Lenoveau-S530:~/work/testing/pygame-testing$ python test.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Mouse button down: 4
Mouse button up: 4
Mouse button down: 4
Mouse button up: 4
Mouse button down: 4
Mouse button up: 4
Mouse button down: 5
Mouse button up: 5
Mouse button down: 5
Mouse button up: 5
Mouse button down: 5
Mouse button up: 5
```

**Comment by ankith26** [comment] 2020-10-24 03:01
I know where the issue is.
You see, pygame 2 is emulating the MOUSEBUTTON event for the mouse wheel, because SDL2 decided to send a new event for mousewheel called MOUSEWHEEL (which you probably should be using). Pygame is emulating the old event just for backwards compatibility, but it’s not emulating the MOUSEBUTTONUP.

I’ll make a PR to fix this

**Comment by ankith26** [comment] 2020-10-24 03:33
Thanks for reporting the issue, looks like its getting fixed now ;)

**Closed** 2020-10-25 11:12 UTC
Labels: Compatability (Pygame 2), bug
