### ISSUE TITLE
Pygame mixer crashes when loading XM file

### ISSUE THREAD

**Issue by karlb** [pygame/pygame#1317] opened 2019-09-18 09:15 UTC
I'm trying to get some code running again that worked on very old (~10 years ago) pygame versions and noticed that the current pygame mixer crashes when loading an XM file that worked back then:

```
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygame
pygame 2.0.0.dev3 (SDL 2.0.9, python 2.7.16)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> pygame.mixer.init()
>>> assert pygame.mixer.get_init()
>>> pygame.mixer.music.load('data/sound/fdream.xm')
Fatal Python error: PyEval_SaveThread: NULL tstate
Aborted
```
The file can be found at https://github.com/karlb/castle-combat/blob/master/data/sound/fdream.xm

**Related Docs:** https://www.pygame.org/docs/ref/mixer.html

**Comment by robertpfeiffer** [comment] 2019-11-04 14:50
This seems to be the same bug as #1211

**Comment by MyreMylar** [comment] 2020-10-29 09:45
Test program:

```
import pygame


pygame.init()

window = pygame.display.set_mode((120, 120))

pygame.mixer.music.load('fdream.xm')
pygame.mixer.music.play()

running = True

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    pygame.display.update()
```

Can't reproduce the reported crash now on windows, pygame 2.0.0, python 3.9. Does this work now for you @karlb ?

**Comment by ankith26** [comment] 2021-11-15 16:18
This issue is fixed in the latest pygame version (just like the linked duplicate issue)

**Closed by ankith26** 2021-11-15 16:18 UTC
Labels: bug, mixer, mixer.music, confirmed/reproducible, needs-investigation, Difficulty: moderate
