### ISSUE TITLE
pygame 1.9.5 on Mac, opens window, sets caption, but will not draw or fill

### ISSUE THREAD

**Issue by tblumer** [pygame/pygame#969] opened 2019-04-07 01:50 UTC
On Mac OS X 10.14.3 Mojave
$ python3 -V
Python 3.7.3
$ pip3 -V
pip 19.0.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

$ python3 example.py
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html

## example.py code: opens window but never draws, no errors
import pygame
import sys
pygame.init()
screen = pygame.display.set_mode((612,792)) # shows window
pygame.display.set_caption("This works!") # shows caption
screen.fill((255,0,0)) # does nothing
pygame.draw.lines(screen, black, False, [(100,100), (150,200), (200,100)], 1) # does nothing
pygame.display.update() # nothing drawn
while (True):
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit(); sys.exit();

Any workaround? Any more info you want? thanks, would love to get this working...

**Comment by yarwest** [comment] 2019-04-08 15:54
I have the same issue, my existing project stopped working. @tblumer did you happen to find out any way to resolve this?

**Comment by tblumer** [comment] 2019-04-08 20:29
@yarwest The problem that I see is this: (I am using Mac OS X Mojave 10.14.3)
- pygame 1.9.5 will not work with a homebrew installed python 3.7.3 (I can run pygame, create window, set caption, exit using x at top left of window, but fill and draw do nothing, and no error messages)
- pygame 1.9.5 works fine if I install Python 3.7.3 using the official Mac distribution and installer (64bit only version is what I used), then I have no problems.
If you already have a homebrew install of 3.7.3, you can still install the 3.7.3 official dist. The links in /usr/local/bin (for python3, pip3 etc) that homebrew linked to its Cellar dir, will be replaced by links to /Library/Frameworks/Python.framework/... by the official Python installer. And then you use the new pip3 from the official install to install whatever python modules you need. So its a bit ugly, and homebrew may give warnings about this, but both versions will still run. In my case python3 will point to the official version, but if I set up alternate links to the homebrew version I can use that one also.
Not sure why the homebrew version does not work, but my guess is that the install of xcode that preceded my homebrew install (both done well before Mojave upgrade) might be the issue.
I wonder if a complete reinstall of xcode, then homebrew, then every homebrew package I need, would fix this? But not sure it is worth the hassle - advice from anyone who has ever "started over" with homebrew would be welcome!

**Comment by husano896** [comment] 2019-04-09 00:58
related issue #555

**Comment by illume** [comment] 2019-04-14 13:00
Yeah, this is a duplicate of #555 

The work arounds are using the official python, python 3.6.x from homebrew, or compiling from source with SDL2.

**Closed by illume** 2019-04-14 13:00 UTC
