### ISSUE TITLE
Compatibility with all Ludum Dare 46 PyGame games

### ISSUE THREAD

**Issue by robertpfeiffer** [pygame/pygame#1737] opened 2020-05-15 07:47 UTC
This is a meta-issue. I tried to play and rate all PyGame-based Ludum Dare entries this year, and I found a couple that didn't work with Pygame 2.0:

- https://ldjam.com/events/ludum-dare/46/broken-threads **BE CAREFUL TO ONLY RUN THIS IN A SANDBOX, IT HAS ANNOYING METAGAME ELEMENTS THAT COULD LEAD TO DATA LOSS** 
- https://ldjam.com/events/ludum-dare/46/supermarket-showdown
- https://ldjam.com/events/ludum-dare/46/sidekick
- https://ldjam.com/events/ludum-dare/46/keep-reputation-alive

Bug Finding status:
- [x] Broken Threads: behaviour of set_alpha(), will be fixed by #1681 
- [x] Supermarket Showdown: It runs, but it doesn't look right
- [x] SideKick: Something breaks, maybe the bug is in pygame.draw.rect
- [x] Keep Reputation Alive

When we have identified the bugs and made tests cases/issues/pull requests, we can close this meta-issue.

Bug Fixing status:
- [x] Broken Threads 
- [x] Supermarket Showdown
- [x] SideKick
- [x] Keep Reputation Alive

**Comment by MyreMylar** [comment] 2020-05-15 08:15
For Supermarket Showdown the problem appears to be that using:

`image.set_colorkey()`

Worked on 32 bit surfaces in pygame 1, but only works on 24 bit surfaces in pygame 2.

**Comment by MightyJosip** [comment] 2020-05-15 09:22
About SideKick: when I run his code with pygame 2 I could move my player, but I could never start the game. So I replaced this line: https://github.com/superduperpacman42/SideKick/blob/105d9d5803cc4e902012f1bc55175587423f220d/Game.pyw#L435 with `if event.type == pygame.KEYDOWN:` And then I was able to run the game. On pygame 1.9.6 both == and is works, but on pygame2 you can only use == to check the type of the event

**Comment by MyreMylar** [comment] 2020-05-15 09:30
Here is a test that passes on pygame 1.9.6 and fails on pygame 2.0.0.dev8 for the colour key issue:

        # create an alpha surface with a white background and a red square
        # in the middle
        pygame.display.init()
        display_surf = pygame.display.set_mode((32, 32))
        src_image = pygame.Surface((16, 16)).convert_alpha()
        src_image.fill(pygame.Color(255, 255, 255))
        src_image.fill(pygame.Color(255, 0, 0), pygame.Rect(4, 4, 8, 8))

        # This surface should have no alpha after converting
        dst_image = pygame.Surface((32, 32)).convert()
        dst_image.fill(pygame.Color(0,0,0))
        dst_image.blit(src_image, (0, 0))
        dst_image.set_colorkey(pygame.Color(255, 255, 255))

        display_surf.blit(dst_image, (0,0))

        # pixel at 17,17 should be opaque black after blitting,
        # if colour key works
        self.assertEqual(display_surf.get_at((0, 0)), pygame.Color(0,0,0))

I noticed that if you toggle this line:

    src_image = pygame.Surface((16, 16)).convert_alpha()

to `convert()` then it will pass on both which suggests that blitting a surface with alpha onto an surface without alpha is copying some sort of flag over to the destination that interferes with the colour key.

**Comment by robertpfeiffer** [comment] 2020-05-15 10:24
> About SideKick: when I run his code with pygame 2 I could move my player, but I could never start the game. So I replaced this line: https://github.com/superduperpacman42/SideKick/blob/105d9d5803cc4e902012f1bc55175587423f220d/Game.pyw#L435 with `if event.type == pygame.KEYDOWN:` And then I was able to run the game. On pygame 1.9.6 both == and is works, but on pygame2 you can only use == to check the type of the event

The `is` is a bug on the developer. I found that too. I had another problem with SideKick causing a segfault

**Comment by robertpfeiffer** [comment] 2020-05-15 10:27
> which suggests that blitting a surface with alpha onto an surface without alpha is copying some sort of flag over to the destination that interferes with the colour key.

Maybe this is relevant to solarwolf. #721

**Comment by MightyJosip** [comment] 2020-05-27 21:46
@robertpfeiffer Can you try to run SideKick now that you did changes to pygame.draw.rect (if you think this is the reason) and see if the game still crashes (because I am unable to reproduce it).

**Comment by MyreMylar** [comment] 2020-10-23 20:03
Supermarket Showdown now works with the 2.0.0.dev22. Tested on windows. 

Probably worth retesting all of these to see how we are doing.

**Comment by MyreMylar** [comment] 2020-10-26 13:54
I get no segfaults with SideKick now either on windows.

**Comment by MyreMylar** [comment] 2020-10-26 14:05
Keep Reputation Alive now looks the same on 1.9.6 as it does on the current dev version.

**Comment by MyreMylar** [comment] 2020-10-26 14:06
All these games seem fine now so may as well close this.

**Closed by MyreMylar** 2020-10-26 14:06 UTC
Labels: Compatibility (Pygame 1), Difficulty: moderate, bug, needs-investigation
