### ISSUE TITLE
Mouse pointer with mouse.set_visible(False) appears at screen edges when using SCALED flag & scaled desktop

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1479] opened 2019-11-02 07:31 UTC
Reported by AtlasDiseaseToday on discord. 

> Found an issue with Pygame 2.0.0.dev6 on Windows 10 in which after calling pygame.mouse.set_visible(False) the mouse sometimes appears (seemingly at random) when moving the mouse (I noticed this happens more when the mouse's x position is at 0).

**Related Docs:** https://www.pygame.org/docs/ref/mouse.html#pygame.mouse.set_visible

**Comment by mcpalmer1980** [comment] 2019-11-06 20:09
It seemed as though this could be a bug introduced by my changes in #1457. I did some testing in Linux Mint 18.3 and Windows 10 but failed to produce unexpected behavior. The cursor never appeared when the mouse was hidden and grabbed. It appeared outside of the window area when hidden only, which is expected behavior.

With a maximized window the cursor will appear along the very edges when the mouse is moved there while the mouse is hidden but input is not grabbed. This is the closest thing to AtlasDiseaseToday's report that I witnessed. Note that I was not running the official dev6 release, but the dev5 artifacts compiled for #1457.

**Comment by illume** [comment] 2019-12-06 18:54
AtlasDisease
> New information about pygame.mouse.set_visible() error in which the cursor would reappear seemly at random. I've found that it reappear if the mouse would be off screen. In the app that I use to test Pygame 2, I hide the system cursor and create a sprite that becomes my cursor used in app. My cursor uses a higher sensitivity (instead of the system sensitivity 1x, it uses 1.4x) which seems to make the system cursor reappear when it would receive a negative number. Don’t know if that makes sense but that it the info I gathered.

**Comment by MyreMylar** [comment] 2020-04-30 16:15
I believe that this bug is related to using the SCALED flag and having a scaled desktop. The only time I saw unexpected behaviour was when using a scaled desktop with the scaled flag. All other tests I tried behaved normally.

**Test Case** (must have windows desktop scaled to something other than 100%):

    import pygame
    
    pygame.init()
    window_surface = pygame.display.set_mode((1920, 1080), flags=pygame.FULLSCREEN | pygame.SCALED)
    
    background = pygame.Surface((1920, 1080))
    background.fill(pygame.Color('#fb8691'))
    
    fake_cursor = pygame.Surface((32, 32))
    fake_cursor.fill(pygame.Color('#88CA99'))
    
    pygame.mouse.set_visible(False)
    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
            if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                pygame.quit()
    
        window_surface.blit(background, (0, 0))
    
        window_surface.blit(fake_cursor, pygame.mouse.get_pos())
        pygame.display.update()
    
You may also want to set the screen resolution to your normal monitor resolution. Anyway with that in place when I move the cursor to the edges of the screen and push at the edges the mouse cursor will flicker in and out of visibility.

I'm tagging in @robertpfeiffer since they did something with the mouse and get_pos(). 

The results from get_pos() seem OK, but I guess SDL thinks the mouse is outside the window and is turning the pointer visible again in this set of circumstances.

**Comment by MyreMylar** [comment] 2020-05-31 13:46
SCALED behaviour has changed recently so I'm going to retest this in case it got fixed.

**Comment by MyreMylar** [comment] 2020-06-01 08:38
Nope, this still happens with the test code above.

**Comment by AtlasDisease** [comment] 2020-07-13 23:58
I finally made a Github account. I'm the user on the Discord that reported the bug to illume. The bug as of Pygame 2.0.0.dev10 has been fixed (for me anyway).

**Comment by MyreMylar** [comment] 2020-10-22 16:52
I tried this again today and I figured out why it happens, it's the `SDL_WINDOW_FULLSCREEN_DESKTOP` flag. 

When you use the `SCALED` and `FULLSCREEN` flags in `set_mode()` you don't actually open a classic full screen video mode, instead you open a borderless window with the same dimensions as the screen. This makes some things work better, but also breaks this. I tried fixing it with a call to: 

`SDL_SetWindowGrab(win, SDL_TRUE);`

But that doesn't work either. Something is a pixel or so out in the calculations of where the SDL & Windows think the mouse is when the display is scaled via the OS - so you get the flickering.

One thing you can do is call `pygame.mouse.set_grab()` which puts the mouse into relative mode when it is hidden. This will fix the cursor appearing at screen edges issue, but will mean the mouse movement no longer has your OS mouse settings.

**Comment by MyreMylar** [comment] 2020-10-26 20:04
Think I just found a fix for this. Will make a quick PR.

**Closed** 2020-10-27 14:56 UTC
Labels: Difficulty: moderate, Windows, bug, display, mouse
