### ISSUE TITLE
pygame 2.0.2.dev1 K_PLUS missing from SDL2 constants in src_c/constants.c

### ISSUE THREAD

**Issue by flowerbug** [pygame/pygame#2622] opened 2021-06-10 17:00 UTC
I was trying to get volume up and down tied to K_PLUS and K_MINUS but K_PLUS would not work for some reason so eventually I found that it was missing from the constants.

**Comment by yasuomaidana** [comment] 2021-06-10 23:40
Could you assign it to me?

**Comment by Starbuck5** [comment] 2021-06-10 23:41
@flowerbug  I'd like to investigate this more.

For your case, just use the `unicode` attribute of the `KEYDOWN` events

**Comment by flowerbug** [comment] 2021-06-10 23:55
thanks, i'm glad for once it wasn't just me goofing up somehow.   :)

**Comment by Starbuck5** [comment] 2021-06-11 00:04
Ok, new conclusion: `event.key` represents physical keys. The docs call it `an integer ID representing every key on the keyboard.` Pygame has all these constants for keys that aren't physical keys on standard keyboards, just in case. So if you can never get `K_PLUS` from your keyboard because you have to press shift and =, that's by design... Although it is confusing.

I wonder if this could be changed? It might be impossible because of backwards compatibility.

**Comment by yasuomaidana** [comment] 2021-06-11 00:22
O thanks you, I'll work on that. Thanks !! 😄

**Comment by flowerbug** [comment] 2021-06-11 14:49
Thank you @Starbuck5 the unicode worked for me.

The following comment in the docs is about pygame 2 and about TEXTINPUT and the text attribute.  
"New in pygame 2.0.0: The pygame.TEXTINPUT event is preferred to the unicode attribute of pygame.KEYDOWN. The attribute text contains the input."

Now it would look like I'd have to have separate conditions being tested for for input from a key press instead of just using the one KEYDOWN.  TEXTINPUT doesn't have anything for K_F2 and the other function keys that don't enter actual text.

The following code snippet from my program is currently just using KEYDOWN:

'''
                                        elif event.key == K_RIGHT:
                                                if self.menu_cursor == 0:
                                                        self.inc_level()    
                                                        self.draw_menu()    
                                        elif event.unicode == "+" or event.key == K_KP_PLUS:
                                                if music_volume < 1.0: 
                                                        music_volume +=0.1
                                                        pygame.mixer.music.set_volume(music_volume)
                                        elif event.unicode == "-" or event.key == K_KP_MINUS:
                                                if music_volume > 0.0: 
                                                        music_volume -=0.1  
                                                        pygame.mixer.music.set_volume(music_volume)
 '''

If I went by the above recommendation I'd have to break those tests apart under two different input events KEYDOWN and TEXTINPUT, which is just kinda silly IMO...  :)

**Comment by robertpfeiffer** [comment] 2021-06-13 08:32
> If I went by the above recommendation I'd have to break those tests apart under two different input events KEYDOWN and TEXTINPUT, which is just kinda silly IMO... :)

So there was some discussion on discord about this after you posted this, and I would just like to remind you, @flowerbug, that not all keyboards are US layout, and not all characters in all languages can be types on a 105 key keyboard, and not all input methods translate into key events. TEXTINPUT exists to handle IME and stroke recognition and android autocorrect and all kind of things. I have a keyboard with a plus key, it's a + sign printed in the centre of the keycap. It's right next to Ü, Ä, and #.

There is no getting around this kind of complexity, and any "Just do what I mean" solution will screw over anybody who uses more than 7-bit ASCII on an EN_US locale. The key.unicode property is *already* a hack that does not account for certain types of text entry. It's fine in this case, but if you want people to enter actual text, like maybe their name, you need TEXTINPUT. If you want people to press a key to change volume, it's probably fine to use the unicode property. I don't think anybody wants to change volume with an on-screen keyboard, stroke recognition, or an emoji selection widget.

I tested my own "plus" key with `examples/eventlist.py` and I found that it works fine, with keycode 43 and scancode 4096.

**Closed by robertpfeiffer** 2021-06-13 08:32 UTC
Labels: key, wontfix

**Comment by flowerbug** [comment] 2021-06-14 12:33
I'm ok with knowing that and am aware of these issues.

@robertpfeiffer I'm not sure if the overall bug of the missing constant was fixed or not though (of the missing K_PLUS constant from SDL2).
