### ISSUE TITLE
pygame.error: Invalid joystick device number --not detecting my joystick

### ISSUE THREAD

**Issue by hariharan382** [pygame/pygame#2799] opened 2021-10-25 06:05 UTC
i am unable to detect my joystick in pygame
joystick:logitech attack 3
i could detect the bttons in linux ,and windows logitech jostick checker but pygame not detecting it please help me in this

```
import pygame

pygame.init()
print("Joystics: ", pygame.joystick.get_count())
my_joystick = pygame.joystick.Joystick(0)
my_joystick.init()
clock = pygame.time.Clock()

while 1:
    for event in pygame.event.get():
        print(my_joystick.get_axis(0),  my_joystick.get_axis(1))
        clock.tick(40)

pygame.quit ()

```

**Comment by ankith26** [comment] 2021-12-31 04:40
Thanks for the bug report! Can you post more info about your system, and the python/pygame/SDL version you are using? If you are not on the latest version already, please test with the latest version to see if the issue is reproducible there

**Comment by Flatout73** [comment] 2022-01-23 22:53
I have same issue on Mac OS 12.1, Pygame 2.1.2, python 3.9

**Comment by MyreMylar** [comment] 2022-07-16 22:41
closing this as we never got any details from the OP and there are other, better 'my joystick/gamepad isn't working on Mac' type issue.

**Closed by MyreMylar** 2022-07-16 22:41 UTC
Labels: bug, Submodule: joystick, needs-op-input
