### ISSUE TITLE
Segfault in error handling of font_init()

### ISSUE THREAD

**Issue by mgorny** [pygame/pygame#1915] opened 2020-06-04 14:23 UTC
When trying to run tests on top of 1.9.6, I get segfault. Debugging it, I've been able to come to the conclusion that it happens in `font_init()`. If `font_resource()` returns `NULL`, the code `goto`es into `error` that attempts to `Py_DECREF(obj);` (which is `NULL`). Hence, program segfaults.

Stepping through the crashing function:
```gdb
Thread 1 "python" hit Breakpoint 1, font_init (self=0x7ffff3207770, Python Exception <class 'gdb.error'> There is no member named ob_digit.: 
args=, kwds=0x0) at src_c/font.c:658
658	{
(gdb) n
660	    TTF_Font *font = NULL;
(gdb) 
663	    PyObject *oencoded = NULL;
(gdb) 
666	    self->font = NULL;
(gdb) 
667	    if (!PyArg_ParseTuple(args, "Oi", &obj, &fontsize)) {
(gdb) 
671	    if (!font_initialized) {
(gdb) 
676	    Py_INCREF(obj);
(gdb) 
678	    if (fontsize <= 1) {
(gdb) 
682	    if (obj == Py_None) {
(gdb) 
683	        Py_DECREF(obj);
(gdb) 
684	        obj = font_resource(font_defaultname);
(gdb) 
685	        if (obj == NULL) {
(gdb) 
686	            if (PyErr_Occurred() == NULL) {
(gdb) 
691	            goto error;
(gdb) 
790	    Py_XDECREF(oencoded);
(gdb) 
791	    Py_DECREF(obj);
(gdb)
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff55374f9 in _Py_DECREF (filename=0x7ffff553a0e2 "src_c/font.c", lineno=791, op=0x0) at /usr/include/python3.8/object.h:470
470	    if (--op->ob_refcnt != 0) {
```

**Comment by MyreMylar** [comment] 2020-06-04 14:27
**Questions:**

1. Which platform?
2. Which test segfaults?
3. What version of python? 

I mean technically this may be expected behaviour because the tests (I'm assuming you are using the latest tests) are keeping pace with the current master branch not 1.9.6 which was released a  while ago. However it may be that this test still fails on some currently active combo of platform/version.

**Comment by mgorny** [comment] 2020-06-04 15:11
> **Questions:**
> 
> 1. Which platform?

Gentoo Linux, upgraded today.

> 2. Which test segfaults?

I'm sorry for assuming it obvious, it's `pygame.tests.font_test`.

> 3. What version of python?

I've reproduced it with:
- 3.6.10
- 3.7.7
- 3.8.3

Python 2.7 fails on some encoding issue, Python 3.9 doesn't build it (`error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’`) but that's outside the topic.

> I mean technically this may be expected behaviour because the tests (I'm assuming by 'tests' you are using the latest tests from the github repo?) are keeping pace with the current master branch not 1.9.6 which was released over a year ago.

No, I'm using the tests from 1.9.6 (`python -m pygame.tests`). As investigated above, this is clearly a problem with the code. I suppose it's failing because it tries to load a font I don't have (freesans, apparently). I have no clue where it gets font names from but it might be an outdated cache somewhere on my system. But in either case, the code shouldn't segfault.

**Comment by MyreMylar** [comment] 2020-06-04 15:31
> I'm sorry for assuming it obvious, it's `pygame.tests.font_test`.

That narrows it down a bit, but generally the test modules print out output for each unit test they run - unless it is failing right at the start, which looking over the stack trace may be the case as that looks like `font_init()`.

> No, I'm using the tests from 1.9.6 (`python -m pygame.tests`). As investigated above, this is clearly a problem with the code. I suppose it's failing because it tries to load a font I don't have (freesans, apparently). I have no clue where it gets font names from but it might be an outdated cache somewhere on my system. But in either case, the code shouldn't segfault.

The default font 'freesansbold.ttf' should be included in the python package by default.

For instance for me, on windows, it's at:

`C:\Users\my-user-name\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pygame\freesansbold.ttf`


Still, you are correct that the code shouldn't segfault if the default font can't be found for some reason. It looks like the code intends to raise an assert in that case, but perhaps that assert is not functioning, or at least was not in version 1.9.6.

I'll have a go at deleting the default font and seeing what happens in the current master branch.

**Comment by MyreMylar** [comment] 2020-06-04 17:16
It probably only gets copied by `setup.py install` is my guess. 

I can reproduce the segfault with 1.9.6 by deleting the font, but not with 2.0.0.dev10 using SDL1 or SDL2 doing the same thing.

 I think I know why it happens on 1.9.6 (the error handling code for font.c is expecting a return value from `pkgdata.py` but it never gets one because pkgdata.py asserts during `open()` and never returns anything) but it seems that 2.0.0.dev10 is no longer bothered by this and just prints out the assert from pkgdata.py without segfaulting. Perhaps a change elsewhere has fixed the underlying cause of the segfault.

Anyway, I probably shouldn't mess with the font code to try and fix an error that no longer happens in the latest code. I don't think this is a major issue for 1.9.6 either really as the vast majority of users will have the default font installed. If we ever do a 1.9.7 it looks like it will probably get fixed without any changes.

**Comment by MyreMylar** [comment] 2020-06-04 18:51
> It probably only gets copied by `setup.py install` is my guess.

Yeah, this is exactly what happens. All the data is only copied around when you use install rather than build. It's been deliberately setup this way, probably because there is a lot of data beyond just the font with all the docs and such like.

I don't think there is any work for pygame to do here? 

 - The segfault on missing font issue is fixed in the current branch.
 - The missing font issue is fixed by using `python setup.py install`.

**Comment by MyreMylar** [comment] 2020-06-07 21:04
Closing as there is no work to do in current version.

**Closed by MyreMylar** 2020-06-07 21:04 UTC
Labels: C code, bug, font
