### ISSUE TITLE
Xbox One controller uses same axis for both triggers

### ISSUE THREAD

**Issue by Sitryk** [pygame/pygame#1096] opened 2019-06-07 09:01 UTC
Is this an issue with the XB1 controller or pygame not reading something correctly?
I had my friend run the example file that shows number of axes and axis values etc. but the trigger axes are changing a single value, resulting in the value increasing when one is pressed and one decreasing the value when it is pressed. This also raises an issue that the value when both triggers are down is equal to the value of both triggers are resting. I'd really like to support most controllers in my software. He was using python 3.7.3 & pygame 1.9.6

**Comment by notpygame** [comment] 2019-06-07 14:05
Some info from blubberquark, 
> partially a driver issue. It also happens with the 360 gamepad on Linux if you use the wrong driver

Additionally, you might want to try pygame 2 pre release. What OS?

**Comment by Sitryk** [comment] 2019-06-07 14:12
Yeah I saw some other xbox issue saying that pygame2 is getting a better controller module, will be unfortunate if I have to rewrite a lot of code.

Windows 10 - I'll get any other needed info from my friend today some time as its 2am currently

**Comment by illume** [comment] 2019-06-08 11:02
Hi,

I think there have been improvements in SDL 2 without using the new game
controller API.

There are windows binaries of a prerelease available, so you don’t need to
compile it yourself to try.

pip install pygame==2.0.0.dev1 —pre


cheers,

**Comment by Sitryk** [comment] 2019-06-08 20:49
I've just installed to test on my machine and first thing I notice with my PS4 Controller is that the D-PAD is no longer recognised as a Hat and the triggers are now only axes and aren't considered buttons. This seems like a great improvement already even though I'll have to rewrite a bit of code. When I can test with my friend I will get info from him for a few controllers. Cheers guys

**Comment by robertpfeiffer** [comment] 2019-11-25 18:46
https://docs.microsoft.com/en-us/windows/win32/xinput/xinput-and-directinput?redirectedfrom=MSDN

> The combination of the left and right triggers in DirectInput is by design. Games have always assumed that DirectInput device axes are centered when there is no user interaction with the device. However, the Xbox controller was designed to register minimum value, not center, when the triggers are not being held. Older games would therefore assume user interaction.
> 
> The solution was to combine the triggers, setting one trigger to a positive direction and the other to a negative direction, so no user interaction is indicative to DirectInput of the "control" being at center.

**Comment by MyreMylar** [comment] 2020-05-10 10:40
Sounds like this is a case of 'feature not a bug' in SDL 1 (it's DirectInput driver behaviour which pygame can't change) and it is a much better situation overall in SDL 2.

I think we should close this.

**Comment by MyreMylar** [comment] 2020-05-16 09:25
Closing as this was a driver issue.

**Closed by MyreMylar** 2020-05-16 09:25 UTC
Labels: joystick
