### ISSUE TITLE
can't install in Termux (mobile development)

### ISSUE THREAD

**Issue by s33wagz** [pygame/pygame#1163] opened 2019-07-15 00:09 UTC
![Screenshot_20190714-170859_Termux](https://user-images.githubusercontent.com/18375750/61191024-318b7000-a65a-11e9-926f-f5186ec9d21e.jpg)

**Comment by illume** [comment] 2019-07-15 10:42
I can't see the error message because it's probably at the bottom of that text.

Do you have an issue open on the termux github already?

**Comment by s33wagz** [comment] 2019-07-15 23:31
sorry about that, what ur seeing is missing dependencies.

I was able to install the other dependencies but it looks like Termux (a linux environment for Android) as awesome as it is, doesn't yet have sdl_mixer, portmidi, or porttime.

**Comment by robertpfeiffer** [comment] 2019-08-02 13:56
duplicate of #1013

**Comment by illume** [comment] 2019-08-02 18:02
Ok. I'll close this one then.

@s33wagz if you're still interested in this issue, please paste the error in that issue #1013. Sorry, I don't use Termux and haven't gotten around to trying it out.

**Closed by illume** 2019-08-02 18:02 UTC
Labels: other (os)
