### ISSUE TITLE
FULLSCREEN mode shows a black screen in Linux Mint.

### ISSUE THREAD

**Issue by Nikorasu** [pygame/pygame#2538] opened 2021-03-28 03:44 UTC
**Environment:**

- **Operating system** : Linux Mint 20.1 x86_64
- **Python version** : 3.8.5
- **SDL version** : 2.0.14
- **PyGame version** : 2.0.1

**Current behavior:**

If a project is set to run in fullscreen mode, using `pygame.display.set_mode((0,0), pygame.FULLSCREEN)`, instead of running/drawing as intended, only a black fullscreen is displayed. Then upon quitting, objects drawn by project appear for 1 frame before program closes. The same project runs perfectly fine in pygame.RESIZABLE mode.

**Example:**
This code should draw a red screen with a green square in the corner, and supposedly works fine in Windows, however in Linux only a black screen is shown until pressing Esc.
```
import pygame

pygame.init()

screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)

clock = pygame.time.Clock()

while True:
    screen.fill((255,0,0))

    pygame.draw.rect(screen, (0,255,0), [0,0,200,200])
    
    pygame.display.flip()

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit
        if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            pygame.quit()
            raise SystemExit            

    clock.tick(60)
```
**Workarounds:**
I've figured out a couple methods that seem to work-around this issue for now:
EDIT (4/12/21)
This seems to work fine in Linux, no additional toggle_fullscreen() line needed:
`screen = pygame.display.set_mode((pygame.display.Info().current_w, pygame.display.Info().current_h), pygame.SCALED)`

First (old) method requires 2 `toggle_fullscreen()` lines after setting the mode to fullscreen. Basically starting with fs mode on, then turning it off and back on again. (the old 'turn it off and on' method lol) (Edit: While this works most the time, in my experience, once in a while it doesn't..)
```
screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
pygame.display.toggle_fullscreen()
pygame.display.toggle_fullscreen()
```

Alternatively this next method seems to work more reliably on my machines, and only needs the `toggle_fullscreen()` once, and uses SCALED, which needs to be given the screen resolution. Not sure why it works better, tho tends to flash the desktop for 1 frame on run, for me.
```
curRez = (pygame.display.Info().current_w, pygame.display.Info().current_h)
screen = pygame.display.set_mode(curRez, pygame.FULLSCREEN | pygame.SCALED)
pygame.display.toggle_fullscreen()
```
Either method seems to jump-start fullscreen into working again, if one doesn't work, try the other. However, as far as I know, those `toggle_fullscreen()` lines aren't supposed to be necessary.. And since this is not the standard method across other platforms.. I assume this is a bug..

**Comment by robertpfeiffer** [comment] 2021-03-29 08:46
Does this run under X11, wayland, or XWayland? What window manager/wayland compositor are you using?

**Comment by robertpfeiffer** [comment] 2021-03-29 09:21
I am 100% confident your problem will go away when you compile PyGame from source, but we haven't found out why that is yet.

**Comment by Nikorasu** [comment] 2021-03-29 12:53
> Does this run under X11, wayland, or XWayland? What window manager/wayland compositor are you using?

Well, I'm not sure about wayland.. However I'm currently using Cinnamon for Linux Mint, which I think is X based..
I've also been told by someone using Ubuntu, that they're also having this problem on their platform, so I don't think it's limited to just Mint or Cinnamon.

> I am 100% confident your problem will go away when you compile PyGame from source, but we haven't found out why that is yet.

Interesting, at least good to know that's an option. Might try compiling from source later.. Although, if there's anything I can do to help narrow this down, please let me know.

**Comment by robertpfeiffer** [comment] 2021-03-29 14:38
Are you using a Nvidia graphics card with the closed source-drivers?

**Comment by Nikorasu** [comment] 2021-03-29 15:44
> Are you using a Nvidia graphics card with the closed source-drivers?
On 1 of my computers, yes, it's using nvidia-driver-450.. However my other computer/laptop does not, and it's just using the open-source drivers for it's intel gpu, also running Linux Mint, and this same fullscreen issue happens on it as well.

**Comment by Nikorasu** [comment] 2021-04-13 00:42
Ok, I've got a minor update.
I just realized that fullscreen can be enabled, by using the pygame.SCALED mode by itself! And doing it that way works perfectly fine in Linux, no workaround required.
`screen = pygame.display.set_mode((pg.display.Info().current_w, pg.display.Info().current_h), pygame.SCALED)`
I feel a little silly about this.. However I haven't come across any documentation or tutorials that actually said to try it this way alone.. which is why it took me this long to figure this out.. :/

**Comment by robertpfeiffer** [comment] 2021-04-14 09:00
> Ok, I've got a minor update.
> I just realized that fullscreen can be enabled, by using the pygame.SCALED mode by itself! And doing it that way works perfectly fine in Linux, no workaround required.
> `screen = pygame.display.set_mode((pygame.display.Info().current_w, pygame.display.Info().current_h), pygame.SCALED)`
> I feel a little silly about this.. However I haven't come across any documentation or tutorials that actually said to try it this way alone.. which is why it took me this long to figure out.. :/

Yeah, SCALED is not *supposed* to be necessary for this. It just happens that SCALED uses the GPU for rendering by copying the display surface to a texture and going from there, while non-SCALED uses the CPU all the way and then sends the pixels to X11 or Wayland a bit later. Ideally, it *should* be the same pixels.

> Well, I'm not sure about wayland.. However I'm currently using Cinnamon for Linux Mint, which I think is X based..

Cinnamon may or may not use wayland as far as I know, as it's based on gnome-shell which can use both, but you are *probably* using X11 directly. Cinnamon was forked from gnome-shell because the Mint people thought the gnome people were a bit too gung-ho about changing things, so the Mint people might want to stick with X11 by default for a little longer. Still, this information might be useful to narrow this down.

**Comment by JovialKnoll** [comment] 2021-05-25 01:50
Is this a duplicate of #2348 ?

**Comment by lym-ay** [comment] 2021-06-08 06:16
yes ,i use SCALED and NOFRAME to do fullscreen.

**Comment by robertpfeiffer** [comment] 2021-06-08 15:34
> yes ,i use SCALED and NOFRAME to do fullscreen.

But surely also FULLSCREEN?

**Comment by anitoanto** [comment] 2021-07-07 16:51
There is a workaround that works for me in Ubuntu 20.04 linux.
`screen = pygame.display.set_mode((0, 0), pyg.NOFRAME)
pygame.display.toggle_fullscreen()`
This will enable full screen.

**Comment by interstellartaurus** [comment] 2021-10-13 14:45
> `pygame.display.set_mode((0, 0), pygame.NOFRAME)`
> `pygame.display.toggle_fullscreen()`

Works for me. Elementary. Replacing the following from Python Crash course practice:

`self.screen = pygame.display.set_mode((0, 0), FULLSCREEN)`
`self.settings.screen_width = self.screen.get_rect().width`
`self.settings.screen_height = self.screen.get_rect().height`

**Comment by illume** [comment] 2021-10-31 13:11
Hoping that this 2.0.3.dev6 pre-release fixes it.
```bash
python3 -m pip install pygame==2.0.3.dev6
```

Is anyone able to test it?

**Comment by interstellartaurus** [comment] 2021-10-31 13:13
I can try to test today.

**Comment by illume** [comment] 2021-10-31 14:05
Thanks @interstellartaurus 

If you run python3 -m pygame.examples.aliens and press 'f' key, it should go fullscreen and you see the game.

**Comment by interstellartaurus** [comment] 2021-10-31 14:16
It works!

**Comment by ankith26** [comment] 2021-10-31 14:17
Nice to hear it works! Thanks again for testing and reporting, this means that this issue can be closed now

**Closed by ankith26** 2021-10-31 14:17 UTC
Labels: bug

**Comment by nlfortier** [comment] 2022-04-02 02:47
This issue still occurs for me on the following pygame version:
pygame 2.1.2 (SDL 2.0.16, Python 3.8.0)
