### ISSUE TITLE
Delete `svn_log_to_whatsnew.py` from the repo

### ISSUE THREAD

**Issue by MyreMylar** [pygame/pygame#2288] opened 2020-10-31 16:16 UTC
I don't think this file is useful anymore as all it did was generate slightly more readable change lists from SVN commits.

We are no longer using svn and clearly nobody has used this script in a while as it was still written in python 2.

**Comment by ankith26** [comment] 2020-10-31 17:13
It’s a duplicate of #2289 :)

**Closed by ankith26** 2020-10-31 17:13 UTC
Labels: Code robustness, Difficulty: Easy, Linters
