### ISSUE TITLE
gearhead-caramel segfault

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1490] opened 2019-11-07 06:46 UTC
There's a segfault in here with python 2.
https://github.com/jwvhewitt/gearhead-caramel

When you go outside. 2.0.0.dev6

**Related Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.copy

**Comment by nthykier** [comment] 2020-04-26 21:00
This could be related to #1200.  Gearhead-caramel uses `pygame.transform`, which _could_ trigger a crash if the surface had a color key, was blit'ed and then used in a certain way after that (e.g. copied).

Can you reproduce the crash after applying the sample patch, I suggested in #1200?

**Comment by jwvhewitt** [comment] 2020-05-12 13:03
I just tried this again with pygame 2.0.0.dev8, and the segmentation fault happens when a bitmap is copied.
![BUG_SegFault](https://user-images.githubusercontent.com/1691593/81694518-6051bd00-949c-11ea-9932-3e43624e1037.png)

**Comment by MyreMylar** [comment] 2020-05-12 14:35
> I just tried this again with pygame 2.0.0.dev8, and the segmentation fault happens when a bitmap is copied.
> ![BUG_SegFault](https://user-images.githubusercontent.com/1691593/81694518-6051bd00-949c-11ea-9932-3e43624e1037.png)

What type is self.bitmap? A pygame.Surface?

**Comment by jwvhewitt** [comment] 2020-05-12 14:37
Yes, sorry. I should have mentioned that.

**Comment by MyreMylar** [comment] 2020-05-12 14:55
So to summarise, this happens with Python 2 on linux, in the latest release of pygame 2 with Surface.copy() in the project gearhead-caramel and may be fixed by this change:

https://github.com/pygame/pygame/issues/1200#issuecomment-619622588

But that has not yet been tested.

**Comment by jwvhewitt** [comment] 2020-05-13 01:48
I should have also mentioned that the game has been switched to Python3, currently testing with Python 3.8. I disabled RLE and now it doesn't crash, so this does seem to be the same bug as #1200 .

**Comment by ankith26** [comment] 2021-11-14 07:55
Closing because this issue only seems to happen on python2, which we dropped support for

**Closed by ankith26** 2021-11-14 07:55 UTC
Labels: Gnu/Linux, segfault, needs-testing, Python 2.7.18, Difficulty: Easy
