### ISSUE TITLE
self.rect.x will not increment if it's a very small number (works with negative numbers though)

### ISSUE THREAD

**Issue by joereynolds** [pygame/pygame#2473] opened 2021-02-07 16:34 UTC
- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac):
- Linux
- **Python version** (e.g. 3.7.9, 3.8.5) :
- Python 3.8.5
- **SDL version** (e.g. SDL 2.0.12):
- 2.0.12
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6):
- 2.0.0

**Current behavior:**

Hello, I seem to have discovered a bug with adding a very small number to a `rect`s `x` (and possibly `y`, have not checked the y.) coordinate.

When I add 0.016 to a rect's `x` the sprite will not move. -0.016 is fine but the positive version fails.

To clarify all I'm doing is 

```
 self.rect.x +=  0.016
```

and seeing no change in the sprite's position. This call is in an `update` method called every loop.

**Expected behavior:**

When I add 0.016 to a rect's `x` it should move by that amount.

**Screenshots**

Here is the sprite (the red square(s)) happily moving along with `-0.016` as its argument:

![pygame-bug-1-2021-02-07_16 17 18](https://user-images.githubusercontent.com/9536682/107152490-2268c300-6960-11eb-891d-961f0491c163.gif)

Likewise here is the exact same thing but with `0.016` as the argument

![pygame-bug-1-actual-2021-02-07_16 19 45](https://user-images.githubusercontent.com/9536682/107152533-62c84100-6960-11eb-8b09-1603c098381a.gif)

**Test code**
```
import pygame

pygame.init()

class Entity(pygame.sprite.Sprite):
    def __init__(self, x, y):
        pygame.sprite.Sprite.__init__(self)
        self.image = pygame.Surface((40, 40)).convert()
        self.image.fill((255,0,0))
        self.rect = self.image.get_rect() 
        self.rect.x = x
        self.rect.y = y

    def update(self):
        self.rect.x += 0.016 # <---- If you change this to -0.016 it will move

clock = pygame.time.Clock()
surface = pygame.display.set_mode((512, 288))

my_sprite = Entity(150,50)
group = pygame.sprite.GroupSingle(my_sprite)

running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            break
            running = False

    surface.fill((0,0,0))
    group.update()
    group.draw(surface)
    pygame.display.flip()
    clock.tick(60)
```

**Comment by zoldalma999** [comment] 2021-02-07 17:09
pygame.Rect stores its attributes as integers. If you want a more precise way of storing position you can use pygame.math.Vector2

**Comment by MightyJosip** [comment] 2021-02-07 17:12
This is because PyGame rects work with ints. So lets say you want to increase your rect value for 0.99. When you write it as `self.rect.x += 0.99` what actually gets done is that it is first converted to integer, and integer value of 0.99 is 0 (you can say casting float to int is the same like taking the floor value of that float. And for -0.001 the float value is -1, and that is why it moves. If you want to use Rect object with float coordinates use it in combination with pygame.math.Vector2 object.

Closing this as ti is not a bug, it is intended result.

**Closed by MightyJosip** 2021-02-07 17:12 UTC
Labels: bug
