### ISSUE TITLE
Flaky test in MixerModuleTest

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pygame/pygame#2358] opened 2020-11-24 07:28 UTC
**Environment:**

In travis continuous integration tests.

**Current behavior:**

During tests we might get:

```
test_sound_args (pygame.tests.mixer_test.MixerModuleTest) ... unexpected success
```

See https://travis-ci.org/github/pygame/pygame/jobs/745481997#L5450

In the test we expect a failure when in fact it seems it fails only sometime:
```python
    # TODO: FIXME: appveyor fails here sometimes.
    @unittest.expectedFailure
    def test_sound_args(self):
        ...
```

**Expected behavior:**

Test fail or succeed consistently

**Comment by zoldalma999** [comment] 2020-11-29 10:30
Connected: #892

**Comment by illume** [comment] 2020-12-01 11:05
Indeed @zoldalma999. This seems a duplicate of #892 I'll close this one.

(please correct me if I'm wrong :)

**Closed by illume** 2020-12-01 11:05 UTC
Labels: bug
