### ISSUE TITLE
pygame 2.0.1 (SDL 2.0.14, Python 3.9.5) Hello from the pygame community. https://www.pygame.org/contribute.html Traceback (most recent call last):   File "C:\Users\harry\OneDrive\桌面\Harry's own folder\Python 3\pokemon6.py", line 17, in <module>     pygame.mixer.music.load("C:/Users/harry/OneDrive/桌面/Harry's own folder/Python 3/01 Opening (part 1).mp3") pygame.error: Failed loading libmpg123-0.dll: The specified module could not be found.   [Finished in 557ms]

### ISSUE THREAD

**Issue by Harry870** [pygame/pygame#2614] opened 2021-05-30 05:43 UTC
I don't know what happend 
here's my code:

import pygame
from PIL import Image, ImageTk
import random
from pygame import mixer

try:
    # Tkinter for Python 2.xx
    import Tkinter as tk
except ImportError:
    # Tkinter for Python 3.xx
    import tkinter as tk

mixer.init()
while True:
    pygame.mixer.music.load("C:/Users/harry/OneDrive/桌面/Harry's own folder/Python 3/01 Opening (part 1).mp3")
    pygame.mixer.music.play()
APP_TITLE = "Pokemon Game"
APP_XPOS = 100
APP_YPOS = 100
APP_WIDTH = 300
APP_HEIGHT = 200
IMAGE_PATH = "images/"
class CreateCanvasObject(object):
    def __init__(self, canvas, image_name, xpos, ypos):
        self.canvas = canvas
        self.image_name = image_name
        self.xpos, self.ypos = xpos, ypos

        #image = Image.open("C:\\Users\\happy\\Desktop\\test.jpg")
        #photo = ImageTk.PhotoImage(image)

        self.tk_image = ImageTk.PhotoImage(
            file="{}{}".format(IMAGE_PATH, image_name))
        self.image_obj= canvas.create_image(
            xpos, ypos, image=self.tk_image)

#        self.tk_image = tk.PhotoImage(
#            file="{}{}".format(IMAGE_PATH, image_name))
#        self.image_obj= canvas.create_image(
#            xpos, ypos, image=self.tk_image)
        canvas.tag_bind(self.image_obj, '<Button1-Motion>', self.move)
        canvas.tag_bind(self.image_obj, '<ButtonRelease-1>', self.release)
        self.move_flag = False
        #self.text_id = self.canvas.create_text(950,50, font='Times 24',text="                                                                 ")
    def move(self, event):
        #self.image_obj[0]:
        #print(self.image_1.x)
        if self.move_flag:
            new_xpos, new_ypos = event.x, event.y
            self.canvas.move(self.image_obj,
                new_xpos-self.mouse_xpos ,new_ypos-self.mouse_ypos)
            self.mouse_xpos = new_xpos
            self.mouse_ypos = new_ypos
        else:
            self.move_flag = True
            self.canvas.tag_raise(self.image_obj)
            self.mouse_xpos = event.x
            self.mouse_ypos = event.y
    def release(self, event):
        self.move_flag = False
class Application(tk.Frame):
    def __init__(self, master):
        #print(self)
        self.master = master
        self.master.protocol("WM_DELETE_WINDOW", self.close)
        tk.Frame.__init__(self, master)
        self.canvas = tk.Canvas(self, width=400, height=400, bg='#AFFAAF',
            highlightthickness=0)
        self.canvas.pack(fill="both", expand=True)
        pokemons = ["Charizard", "Charmeleon", 'Charmander', 'Blastoise', 'Wartortle','Squirtle','Venusaur','Ivysaur','Bulbsaur']
        random.shuffle(pokemons)
        for i in range(0,9):
            self.image_1 = CreateCanvasObject(self.canvas,pokemons[i]+'.png', 100*i+350, 500)
            #self.image_2 =CreateCanvasObject(self.canvas, "Charmeleon.png", 200, 500)
            #self.image_3 = CreateCanvasObject(self.canvas, "Charmander.png", 300, 500)
            #self.image_4 =CreateCanvasObject(self.canvas, "Blastoise.png", 400, 500)
            #self.image_5 = CreateCanvasObject(self.canvas, "Wartortle.png", 500, 500)
            #self.image_6 =CreateCanvasObject(self.canvas, "Squirtle.png", 600, 500)
            #self.image_7 =CreateCanvasObject(self.canvas, "Venusaur.png", 700, 500)
            #self.image_8 = CreateCanvasObject(self.canvas, "Ivysaur.png", 800, 500)
            #self.image_9 =CreateCanvasObject(self.canvas, "Bulbsaur.png", 900, 500)
        self.canvas.create_rectangle(350, 50, 600, 300) # fill='white')
        self.canvas.create_rectangle(650, 50, 900, 300) #, fill='white')
        self.canvas.create_rectangle(950, 50, 1200, 300) #, fill='white')
        self.canvas.create_rectangle(320, 550, 1250, 450)
        self.text_id1 = self.canvas.create_text(500,750, font='Times 24',text="")
        self.text_id = self.canvas.create_text(650,750, font='Times 24',text="")
        self.text_id2 = self.canvas.create_text(800,750, font='Times 24',text="")
        self.text_id3 = self.canvas.create_text(1000,750, font='Times 24',text="")
        self.text_id4 = self.canvas.create_text(800,400, font='Times 24',text="Drag the pokemons in their right evolution place. When you finished, press [Calculate] ")
        set1={pokemons.index('Charizard')+1,pokemons.index('Charmeleon')+1,pokemons.index('Charmander')+1}
        set2={pokemons.index('Blastoise')+1,pokemons.index('Wartortle')+1,pokemons.index('Squirtle')+1}
        set3={pokemons.index('Venusaur')+1,pokemons.index('Ivysaur')+1,pokemons.index('Bulbsaur')+1}

        pokemon_names = []

        def button_event():
            Frame1=[]
            Frame2=[]
            Frame3=[]
            for i in range(1,10): #print out every image object's coordinates
                #print(i, self.canvas.coords(i))
                if self.canvas.coords(i)[0] >= 350 and self.canvas.coords(i)[0] <= 600 and self.canvas.coords(i)[1] >= 50 and self.canvas.coords(i)[1] <= 300:
                    Frame1.append(i)
                if self.canvas.coords(i)[0] >= 650 and self.canvas.coords(i)[0] <= 900 and self.canvas.coords(i)[1] >= 50 and self.canvas.coords(i)[1] <= 300:
                    Frame2.append(i)
                if self.canvas.coords(i)[0] >= 950 and self.canvas.coords(i)[0] <= 1200 and self.canvas.coords(i)[1] >= 50 and self.canvas.coords(i)[1] <= 300:
                    Frame3.append(i)
            TP=0
            FP=0
            Level = 1

          
            

            for i in Frame1:
                for j in Frame1:
                    if i<j:
                        if (i in set1 and j in set1) or (i in set2 and j in set2) or (i in set3 and j in set3):
                            TP+=1
                        else:
                            FP+=1

            Undiscovered=0
            for i in set1:
                for j in set1:
                    if i<j:
                        Undiscovered+=1
                        if (i in Frame1 and j in Frame1) or (i in Frame2 and j in Frame2) or (i in Frame3 and j in Frame3):
                            Undiscovered-=1

            for i in Frame2:
                for j in Frame2:
                    if i<j:
                        if (i in set1 and j in set1) or (i in set2 and j in set2) or (i in set3 and j in set3):
                            TP+=1
                        else:
                            FP+=1

            #Undiscovered=0
            for i in set2:
                for j in set2:
                    if i<j:
                        Undiscovered+=1
                        if (i in Frame1 and j in Frame1) or (i in Frame2 and j in Frame2) or (i in Frame3 and j in Frame3):
                            Undiscovered-=1

            

            for i in Frame3:
                for j in Frame3:
                    if i<j:
                        if (i in set1 and j in set1) or (i in set2 and j in set2) or (i in set3 and j in set3):
                            TP+=1
                        else:
                            FP+=1

            #Undiscovered=0
            for i in set3:
                for j in set3:
                    if i<j:
                        Undiscovered+=1
                        if (i in Frame1 and j in Frame1) or (i in Frame2 and j in Frame2) or (i in Frame3 and j in Frame3):
                            Undiscovered-=1

            self.canvas.itemconfigure(self.text_id,text="Correct: "+str(TP))
            self.canvas.itemconfigure(self.text_id2,text="Incorrect: "+str(FP))
            self.canvas.itemconfigure(self.text_id3,text="Undiscovered: "+str(Undiscovered))
            self.canvas.itemconfigure(self.text_id1,text="Level: "+str(Level))
            #print("TP=", TP, "FP=", FP, "Undiscovered=", Undiscovered)

                    #if self.canvas.coords(i)[0] >= 400 and self.canvas.coords(i)[0] <= 650 and self.canvas.coords(i)[1] >= 400 and self.canvas.coords(i)[1] <= 650:
                        #print(yes)

                      #print(self.image_1.x, self.image_1)
                
            #print(self.image_2.xpos, self.image_2.ypos)
            #print(self.image_3.xpos, self.image_3.ypos)
            #print(self.image_4.xpos, self.image_4.ypos)
            #print(self.image_5.xpos, self.image_5.ypos)
            #print(self.image_6.xpos, self.image_6.ypos)
        self.mybutton = tk.Button(self, text='Calculate your score', width=50, height=5, command=button_event)
        self.mybutton.place(x=600,y=600)
    def close(self):
        print("Application-Shutdown")
        self.master.destroy()
def main():
    app_win = tk.Tk()
    app_win.title(APP_TITLE)
    app_win.geometry("+{}+{}".format(APP_XPOS, APP_YPOS))

    #app_win.geometry("{}x{}".format(APP_WIDTH, APP_HEIGHT))
    #def button_event():
    #    print(app_win.)
#    mybutton = tk.Button(app_win, text='Calculate', command=button_event)#   mybutton.pack()
    app = Application(app_win).pack(fill='both', expand=True)
    app_win.mainloop()
if __name__ == '__main__':
    main()

**Comment by Starbuck5** [comment] 2021-05-30 06:49
Hello,

This is impossible to read because the code is not formatted at all.

Also, we have a bug report template for issues. Please use that.

Thirdly, it is best to create a  "minimal reproducible example" of the problem, rather than putting in 200+ lines of code.

I'm going to close this issue, but if you believe this is a problem with pygame, feel free to create a new one, with a minimal reproducible example, and with use of the bug report template.

**Closed by Starbuck5** 2021-05-30 06:49 UTC
