### ISSUE TITLE
Pygame slow on OSX

### ISSUE THREAD

**Issue by Mh4x** [pygame/pygame#450] opened 2018-05-06 05:02 UTC
There are multiple issues posted and forum posts on the internet about this; just posting another one for vision. This really needs to be fixed, as me and many others may have to stop using pygame entirely.

**Comment by illume** [comment] 2018-05-14 06:02
Duplicate of https://github.com/pygame/pygame/issues/440

**Closed by illume** 2018-05-14 06:02 UTC
