### ISSUE TITLE
can read gamepad only by device name?

### ISSUE THREAD

**Issue by zarlicho** [pygame/pygame#2868] opened 2021-11-27 01:21 UTC
for example I have 3 gamepads and lock 1 gamepad device to read

**Comment by zarlicho** [comment] 2021-11-27 01:51
`import pygame
import sys
from pygame.locals import *
from math import trunc
import vgamepad as vg
import time

gamepad = vg.VDS4Gamepad()
pygame.init()
joysticks = []
clock = pygame.time.Clock()
keepPlaying = True
motion = [0,0]
print("tes")
pygame.joystick.init()
joysticks = [pygame.joystick.Joystick(1) for i in range(pygame.joystick.get_count())]
for i in range(0, pygame.joystick.get_count()):
    # create an Joystick object in our list
    joysticks.append(pygame.joystick.Joystick(i))
    # initialize them all (-1 means loop forever)
    joysticks[1].init()
    print(joysticks[-1])
    # print a statement telling what the name of the controller is
    #print ("Detected joystick "),joysticks[0].get_name(),"'"
    #print(joysticks[-1].get_name())


while True:
    for event in pygame.event.get():
        if event.type == JOYAXISMOTION:
            print(event.axis)
            if event.axis < 2:

                motion[event.axis] = event.value
                xvalue =  motion[0]
                yvalue = motion[1]
                yc = float(yvalue)
                print("X",xvalue,"Y",yc)
                gamepad.left_joystick_float(x_value_float=xvalue, y_value_float=0.0) 
                gamepad.update()
`

**Comment by MyreMylar** [comment] 2021-11-28 09:52
I'm not sure what your problem is here or what you are trying to do. 

Please try and provide more explanation

**Comment by zarlicho** [comment] 2021-11-29 12:50
I mean pygame only reads one selected gamepad device, so if I move the second gamepad the data will not be readable by pygame

**Comment by zoldalma999** [comment] 2021-12-12 12:25
I am as confused on what's the problem here as MyreMylar. Your last example code does not even import pygame. If it is still an issue, can you post what happens right now (so what is the problem) and what you expected to happen, as well as a *short* code example that uses pygame?

**Comment by ankith26** [comment] 2021-12-31 04:34
Closing issue for now, OP feel free to re-open when you can provide more information on this issue, and highlight the pygame function that does not work as intended, as zoldalma says, a short code reproducer :)

**Closed by ankith26** 2021-12-31 04:34 UTC
Labels: joystick, needs-op-input
