### ISSUE TITLE
Enhancement: Reduce pyinstaller exe size

### ISSUE THREAD

**Issue by ankith26** [pygame/pygame#2174] opened 2020-10-12 05:20 UTC
**Description**

#1514 made a change to include all dlls into pyinstaller generated exes. While this solution works, it includes so many dlls on windows that the size of an average pygame app with pyinstaller crossed 45 mb. (Just tried with pygame 2.0.0dev12)

It would be a nice enhancement if only the required dlls were bundled with pygame, in particular, I noticed a dll of size 27 MB, which actually didn’t look like it was useful.

I’m going to open a PR to fix this issue, once I’m able to certain out which dlls are really necessary for pygame to work.
If anyone can help me figure out which dlls are required, I would appreciate it a lot :)

**Comment by ankith26** [comment] 2020-10-12 05:22
And yes, this can be something for post-v2.0.0

**Comment by Starbuck5** [comment] 2020-10-12 17:02
I've noticed that PyInstaller includes numpy and PIL when freezing pygame games.
The DLL you are referring to is probably LIBOPENBLAS, which is a numpy dependency.

This can be fixed on the users end by excluding those imports. pygame can't do it automatically because people might be using numpy or PIL.

I would be surprised if my hook was making this happen, but I suppose it could be. All it really does is ``collect_dynamic_libs('pygame')``

I'll do some testing.

**Comment by ankith26** [comment] 2020-10-13 02:57
Even I will do some testing, what I noticed is that pygame itself automatically loads numpy and other dependencies while running in frozen mode.

**Comment by ankith26** [comment] 2020-10-13 02:59
I just noticed a change in the size of the exe.
In pygame2.0.0dev10, the size of my app was about 20mb, and in
Pygame2.0.0dev12 the size of my app is about 48mb

**Comment by Starbuck5** [comment] 2020-10-15 06:56
Basic pygame program size of executable: (PyInstaller 4.0, not onefile mode, Windows)

|                                                      | 1.9.6   | 2.0.0.dev10 | 2.0.0.dev14 |
|------------------------------------------------------|---------|-------------|-------------|
| Automatic spec file                                  | 73.5 mb | 72.2 mb     | 74.5 mb     |
| Spec file explicitly excluding Numpy, PIL, and scipy | 16.3 mb | 15.0 mb     | 17.3 mb     |

Therefore I don't think the hook is the problem. The extra 2.3 mb after the hook was added allow it to properly load files, and includes the pygame default font and icon.

The problem is Numpy, PIL, and scipy being falsely thought of as dependencies.

**Comment by ankith26** [comment] 2020-10-15 07:18
Hmm yeah, so I guess the size is due to pyinstaller 4.0

**Comment by MyreMylar** [comment] 2020-10-15 08:54
Probably a 'Using PyInstaller with pygame' tutorial on the Wiki briefly explaining spec files, how to exclude Numpy, PIL, scipy and so on would be very useful and widely used.

**Comment by illume** [comment] 2020-10-15 11:31
PIL and numpy are optional dependencies of pygame, so I guess it's in one way correct including them.

They should ultimately only be used when using numpy in the users app (like if surfarray or sndarray is imported). I'm not sure if pyinstaller can be told to do that somehow.

If inside a virtualenv without numpy/PIL, does it still work?

**Comment by robertpfeiffer** [comment] 2020-11-05 10:13
Does PyInstaller inlcude tests/examples/docs by default? Does it incorporate whole PyPI/pip packages or just the DLLs and pyc files that are loaded/imported? I don't know if reducing the build size in setup.py affects PyInstaller the same way it affects p4a.

**Comment by ankith26** [comment] 2020-11-05 10:33
Well, pyinstaller recursively searches program imports to determine which file is to be bundled and which file can be ignored. This also means that, it will not include any non-python file by default, and to include those, we write hooks.

Well, the excessive size of the executable is definitely due to pyinstaller including numpy and PIL (not so sure about scipy, never included that one for me)

**Comment by Starbuck5** [comment] 2020-11-21 04:24
I found an interesting commit message in the PyInstaller 4.1 release notes.
https://github.com/pyinstaller/pyinstaller/commit/f185156e49479aa08a93387553ac327c4be1f17a

If we can assume that pygame features that use numpy require the user to import numpy in their own script, we can use this solution.

**Comment by Starbuck5** [comment] 2022-07-16 08:24
We can't quite assume that I think. And this issue is stale, so I'll go ahead and close.

**Closed by Starbuck5** 2022-07-16 08:24 UTC
Labels: enhancement, PyInstaller
