### ISSUE TITLE
Joystick axis returns 0.0 every time.

### ISSUE THREAD

**Issue by baserubb** [pygame/pygame#513] opened 2018-08-28 20:07 UTC
For a project i need the values of the controller axises while pyGame working in behind. But it always return 0.0. I tried pygame.event.get() instead of pygame.event.pump(), but it is not worked.

**Comment by e1000** [comment] 2018-08-29 07:56
hello @umutbaser ,

it's always useful for debugging to have a maximum of informations, sometimes the bug can happen just on a minor version of OS / Python / Pygame and not the next or previous minor version ... typically: 

* what is your OS + version
* which version of Python & Pygame
* and ideally adding a minimal code example to reproduce the bug.

**Comment by illume** [comment] 2018-08-29 13:31
Does it also return 0.0 with this example?
`python -m pygame.examples.eventlist`

**Comment by MyreMylar** [comment] 2020-05-01 08:46
@baserubb 

Did you ever get this working? Do you still have code and other details of your issue, or should we just close it up?

I don't believe there are any general problems with controller input from joysticks, I've used them successfully in an asteroids clone and for controlling a robot arm.

**Comment by MyreMylar** [comment] 2020-05-12 08:11
Closing for now because it is not a general issue and we have no details to chase down.

**Closed by MyreMylar** 2020-05-12 08:11 UTC
Labels: event, needs-op-input

**Comment by Taffer** [comment] 2021-05-12 11:13
I'm experiencing this too, maybe I can provide more details.

I can see joystick add/remove events and that's it; I can identify the gamepad and count the buttons/axes/hats properly, but none of them register any input.

Confirmed via `python -m pygame.examples.eventlist`.

Pygame/SDL/Python versions:

```
pygame 2.0.1 (SDL 2.0.14, Python 3.9.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
```

OS is Windows 10 20H2. My gamepad is an XBox One wireless connected via Bluetooth. Works fine in Unity and in the ancient Windows joystick settings/calibration control panel. I haven't tested extensively since installing this system.

Here's the code I'm using:

```py
# Experiment 16 - How to Joystick
#
# By Chris Herborth (https://github.com/Taffer)
# MIT license, see LICENSE.md for details.

import pygame
import pygame.freetype
import pygame.gfxdraw
import random
import time
import sys

SCREEN_TITLE = 'Experiment 16 - How to Joystick'

SCREEN_WIDTH = 1280  # 720p screen
SCREEN_HEIGHT = 720

BLACK = pygame.Color('black')
WHITE = pygame.Color('white')


class Demo:
    def __init__(self, screen):
        self.screen = screen

        self.mono = pygame.freetype.Font('resources/LiberationMono-Bold.ttf', 16)

    def draw(self):
        self.screen.fill(BLACK)

        self.mono.render_to(self.screen, (10, 10), 'Move your joystick, press Esc to exit.', WHITE)

        found = pygame.joystick.get_count()
        self.mono.render_to(self.screen, (10, 30), f'Found {found} joystick(s).', WHITE)

        if found > 0:
            joystick = pygame.joystick.Joystick(0)  # This demo only supports the first joystick.
            self.mono.render_to(self.screen, (10, 50), 'Joystick #1:', WHITE)
            self.mono.render_to(self.screen, (20, 70), joystick.get_name(), WHITE)
            self.mono.render_to(self.screen, (20, 90), joystick.get_guid(), WHITE)

            y = 130
            for i in range(joystick.get_numaxes()):
                value = joystick.get_axis(i)
                self.mono.render_to(self.screen, (20, y), f'Axis {i}: {value}', WHITE)
                y += 20

            y += 20
            for i in range(joystick.get_numbuttons()):
                value = joystick.get_button(i)
                if value:
                    self.mono.render_to(self.screen, (20, y), f'Button {i}: Down', WHITE)
                else:
                    self.mono.render_to(self.screen, (20, y), f'Button {i}: Up', WHITE)
                y += 20

            y += 20
            for i in range(joystick.get_numhats()):
                value = joystick.get_hat(i)
                self.mono.render_to(self.screen, (20, y), f'Hat {i}: {value}', WHITE)
                y += 20

    def update(self, dt):
        pass


def main():
    pygame.init()
    random.seed(time.time())

    screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
    pygame.display.set_caption(SCREEN_TITLE)

    demo = Demo(screen)

    now = time.time()
    dt = 0

    playing = True

    while playing:
        demo.draw()
        pygame.display.flip()

        dt = time.time() - now
        now = time.time()

        demo.update(dt)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                playing = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    playing = False

    pygame.quit()
    sys.exit()


if __name__ == '__main__':
    main()
```

Is there any other useful information I can provide?

**Comment by Taffer** [comment] 2021-05-12 20:01
Same behaviour from my Logitech Wireless Gamepad F710; on/off is visible, it can count buttons/axes/etc. but not get any input from any of them.

**Comment by Taffer** [comment] 2021-05-12 20:12
Sample script (https://github.com/pygame/pygame/blob/main/docs/reST/ref/code_examples/joystick_calls.py) from the docs works, so I must be doing something dumb, will report back.

**Comment by Taffer** [comment] 2021-05-13 11:28
The issue seems to be creating the `Joystick` object every iteration; I've fixed it by adding a `self.joystick` to the `Demo` class, which gets initialized once and then just re-used. Victory!
