### ISSUE TITLE
line drawn with aaline is not always "solid" all the way in pygame 2.dev12

### ISSUE THREAD

**Issue by viblo** [pygame/pygame#2120] opened 2020-09-26 19:35 UTC
It seems like aaline drawing in pygame 2 works a bit different compared to pygame 1. The below pictures show 3 lines with different angle, but the issue it can happen at other angles as well.

pygame 2.0.0.dev12 (SDL 2.0.12, python 3.8.4) (On windows)
![image](https://user-images.githubusercontent.com/1195272/94348735-e8e18c00-003e-11eb-8a8f-e34ba304e2bd.png)

pygame 1.9.6
![image](https://user-images.githubusercontent.com/1195272/94348772-52fa3100-003f-11eb-87ae-96fa76c582e3.png)

Code to reproduce:

```python
import pygame

pygame.init()

screen = pygame.display.set_mode((600, 600))

while True:
    for event in pygame.event.get():
        if (
            event.type == pygame.QUIT
            or event.type == pygame.KEYDOWN
            and (event.key in [pygame.K_ESCAPE, pygame.K_q])
        ):
            exit()

    screen.fill(pygame.Color("black"))

    lines = [
        [(200, 175), (93, 401)],
        [(250, 175), (249, 424)],
        [(300, 175), (333, 422)],
    ]

    for p1, p2 in lines:
        pygame.draw.aaline(screen, pygame.Color("lightgray"), p1, p2)

    pygame.display.flip()

```

**Comment by MightyJosip** [comment] 2020-09-27 19:35
Note to myself: (250, 175), (249, 424), but (250, 175), (251, 424) does work. The problem is probably around this line: https://github.com/pygame/pygame/blob/e2ca1bc21dded56016f8443d3ea528207b8d586c/src_c/draw.c#L1164

**Comment by siggisv** [comment] 2020-09-27 22:33
@MightyJosip I had started reading through `draw.c` looking for the cause of this issue before noticing it is now assigned to you.

I did find what was causing this bug and how to fix this but since it was not my intention to steal this issue from you, then I'll allow you the honor of making the PR.

---

In case you had not found it out yet, the issue is cause by those two lines:

https://github.com/pygame/pygame/blob/e2ca1bc21dded56016f8443d3ea528207b8d586c/src_c/draw.c#L1186-L1186

https://github.com/pygame/pygame/blob/e2ca1bc21dded56016f8443d3ea528207b8d586c/src_c/draw.c#L1198-L1198

In both those lines, `(int) intersect_y < to_y` should be `(int) intersect_y < intersect_y`

**Comment by MightyJosip** [comment] 2020-09-28 12:55
Oh thanks @siggisv. You can freely make the PR for it, I don't think I will have time in the following weeks.

**Comment by siggisv** [comment] 2020-09-28 14:57
Ok. Will do.

I should be able to also put together a test that reveals this bug.

**Closed** 2020-10-10 15:07 UTC
Labels: draw

**Comment by viblo** [comment] 2020-10-10 17:56
Thanks for the speedy fix!
