### ISSUE TITLE
Subsurface and sprites refresh

### ISSUE THREAD

**Issue by inigoini** [pygame/pygame#916] opened 2019-03-18 11:58 UTC
When a subsurface is created, using an offset, sprites are displayed properly. But If sprites are moved, then the offset of the subsurface is not applied and sprites ar not displayed properly. 

Example code:

```python
import os
import pygame

pygame.init()

main_surface = pygame.display.set_mode((800, 500))

''' Creates a subsurface '''
surface = main_surface.subsurface((10, 10, 700, 400))

source = pygame.image.load(os.path.join('sprites.png')).convert()

bird = pygame.sprite.DirtySprite()
bird.image = source
bird.image.set_colorkey((255, 0, 255))
bird.source_rect = pygame.Rect(0, 148, 35, 24)
bird.rect = pygame.Rect(100, 100, 35, 24)

background = pygame.Surface((800, 500))
background.fill((40, 0, 0))

layer = pygame.sprite.LayeredDirty()
layer.clear(surface, background)
layer.add(bird)

clock = pygame.time.Clock()

running = True

''' Main game loop '''
while running:

	''' Manages events '''
	events = pygame.event.get()
	for event in events:
		if event.type == pygame.QUIT:
			running = False

	bird.rect = bird.rect.move(2, 0)
	bird.dirty = 1

	rects = layer.draw(surface)

	'''TODO I need to add those lines to run it properly '''
	'''for i, rect in enumerate(rects):
		rects[i] = rect.move(surface.get_offset())'''

	pygame.display.update(rects)

	''' Waits, 10 frames per second '''
	clock.tick(10)

pygame.quit()
```

![sprites](https://user-images.githubusercontent.com/5804984/54528509-7d186080-497d-11e9-808e-f542080944a6.png)

**Related Docs:** https://www.pygame.org/docs/ref/surface.html#pygame.Surface.subsurface

**Comment by MyreMylar** [comment] 2022-07-16 21:05
This code does not move the bird sprite, which is I assume where the confusion arose.

It just moves the rectangles returned from `LayeredDirty.draw()` which is some new rectangles indicating where on the screen was just drawn on. You likely just got some slightly clipped sprite mess from this code.

Incidentally sprite rectangles do not have to be the same size as the sprite's image variable.

Closing this as it is not a bug in pygame, just in this code.

**Closed by MyreMylar** 2022-07-16 21:05 UTC
Labels: bug, Submodule: Surface, needs-investigation, Difficulty: moderate
