### ISSUE TITLE
Can't download pygame

### ISSUE THREAD

**Issue by PatLaCastagne** [pygame/pygame#2755] opened 2021-10-08 18:06 UTC
I can't seem to be able to install pygame on Windows 11

Command used:
`py -m pip install -U pygame --user ` and `py -m pip install pygame`

System
Windows 11
CPU : Ryzen 5 1600 Af

Here is the error log (I cut the end of the error because it was too long) :

```
   ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ulyss\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_0cd70194ed8b4a7b97f24b81a24077c5\\setup.py'"'"'; __file__='"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_0cd70194ed8b4a7b97f24b81a24077c5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ulyss\AppData\Local\Temp\pip-pip-egg-info-ey26ztnz'
         cwd: C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_0cd70194ed8b4a7b97f24b81a24077c5\
    Complete output (69 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...

    Traceback (most recent call last):
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1276, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1322, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1271, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1031, in _send_output
        self.send(msg)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 969, in send
        self.connect()
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1448, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
        return self.sslsocket_class._create(
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
        self.do_handshake()
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_0cd70194ed8b4a7b97f24b81a24077c5\setup.py", line 318, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_0cd70194ed8b4a7b97f24b81a24077c5\buildconfig\config.py", line 221, in main
        deps = CFG.main(**kwds)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_0cd70194ed8b4a7b97f24b81a24077c5\buildconfig\config_win.py", line 559, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_0cd70194ed8b4a7b97f24b81a24077c5\buildconfig\download_win_prebuilt.py", line 275, in ask
        update(x86=x86, x64=x64, sdl2=sdl2)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_0cd70194ed8b4a7b97f24b81a24077c5\buildconfig\download_win_prebuilt.py", line 258, in update
        download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_0cd70194ed8b4a7b97f24b81a24077c5\buildconfig\download_win_prebuilt.py", line 107, in download_prebuilts
        download_sha1_unzip(url, checksum, temp_dir, 1)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_0cd70194ed8b4a7b97f24b81a24077c5\buildconfig\download_win_prebuilt.py", line 40, in download_sha1_unzip
        response = urllib.urlopen(request).read()
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
        response = self._open(req, data)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
        result = func(*args)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
    Making dir :prebuilt_downloads:
    Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.14-VC.zip 48d5dcd4a445410301f5575219cffb6de654edb8

    ---
    For help with compilation see:
        https://www.pygame.org/wiki/CompileWindows
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c7/b8/06e02c7cca7aec915839927a9aa19f749ac17a3d2bb2610b945d2de0aa96/pygame-2.0.1.tar.gz#sha256=8b1e7b63f47aafcdd8849933b206778747ef1802bd3d526aca45ed77141e4001 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-2.0.0.tar.gz (5.5 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ulyss\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_ce42600261f64f9b8de80d1230d757f8\\setup.py'"'"'; __file__='"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_ce42600261f64f9b8de80d1230d757f8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ulyss\AppData\Local\Temp\pip-pip-egg-info-9sbjqebd'
         cwd: C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_ce42600261f64f9b8de80d1230d757f8\
    Complete output (69 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...

    Traceback (most recent call last):
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
        h.request(req.get_method(), req.selector, req.data, headers,
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1276, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1322, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1271, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1031, in _send_output
        self.send(msg)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 969, in send
        self.connect()
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1448, in connect
        self.sock = self._context.wrap_socket(self.sock,
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 512, in wrap_socket
        return self.sslsocket_class._create(
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1070, in _create
        self.do_handshake()
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1341, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_ce42600261f64f9b8de80d1230d757f8\setup.py", line 318, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_ce42600261f64f9b8de80d1230d757f8\buildconfig\config.py", line 221, in main
        deps = CFG.main(**kwds)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_ce42600261f64f9b8de80d1230d757f8\buildconfig\config_win.py", line 559, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_ce42600261f64f9b8de80d1230d757f8\buildconfig\download_win_prebuilt.py", line 275, in ask
        update(x86=x86, x64=x64, sdl2=sdl2)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_ce42600261f64f9b8de80d1230d757f8\buildconfig\download_win_prebuilt.py", line 258, in update
        download_prebuilts(download_dir, x86=x86, x64=x64, sdl2=sdl2)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_ce42600261f64f9b8de80d1230d757f8\buildconfig\download_win_prebuilt.py", line 107, in download_prebuilts
        download_sha1_unzip(url, checksum, temp_dir, 1)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_ce42600261f64f9b8de80d1230d757f8\buildconfig\download_win_prebuilt.py", line 40, in download_sha1_unzip
        response = urllib.urlopen(request).read()
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
        response = self._open(req, data)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
        result = self._call_chain(self.handle_open, protocol, protocol +
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
        result = func(*args)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
        return self.do_open(http.client.HTTPSConnection, req,
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)>
    Making dir :prebuilt_downloads:
    Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip 6839b6ec345ef754a6585ab24f04e125e88c3392

    ---
    For help with compilation see:
        https://www.pygame.org/wiki/CompileWindows
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/0c/d164411381bada8feae57359aa9296defbed3035f4b55bef6a271cb0573c/pygame-2.0.0.tar.gz#sha256=63b038da116a643046181b02173fd894d87d2f85ecfd6aa7d5ece73c6ef501e9 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-1.9.6.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ulyss\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_bb416f7238aa4aec97d730cdc03732d6\\setup.py'"'"'; __file__='"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_bb416f7238aa4aec97d730cdc03732d6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ulyss\AppData\Local\Temp\pip-pip-egg-info-rs197baz'
         cwd: C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_bb416f7238aa4aec97d730cdc03732d6\
    Complete output (17 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...


    Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_bb416f7238aa4aec97d730cdc03732d6\setup.py", line 194, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_bb416f7238aa4aec97d730cdc03732d6\buildconfig\config.py", line 210, in main
        deps = CFG.main(**kwds)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_bb416f7238aa4aec97d730cdc03732d6\buildconfig\config_win.py", line 576, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_bb416f7238aa4aec97d730cdc03732d6\buildconfig\download_win_prebuilt.py", line 302, in ask
        reply = raw_input(
    EOFError: EOF when reading a line
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0f/9c/78626be04e193c0624842090fe5555b3805c050dfaa81c8094d6441db2be/pygame-1.9.6.tar.gz#sha256=301c6428c0880ecd4a9e3951b80e539c33863b6ff356a443db1758de4f297957 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-1.9.5.tar.gz (3.2 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ulyss\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_f527b49a8476400baa043e4012aa9804\\setup.py'"'"'; __file__='"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_f527b49a8476400baa043e4012aa9804\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ulyss\AppData\Local\Temp\pip-pip-egg-info-9w6_xtif'
         cwd: C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_f527b49a8476400baa043e4012aa9804\
    Complete output (17 lines):


    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using WINDOWS configuration...


    Download prebuilts to "prebuilt_downloads" and copy to "./prebuilt-x64"? [Y/n]Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_f527b49a8476400baa043e4012aa9804\setup.py", line 194, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_f527b49a8476400baa043e4012aa9804\buildconfig\config.py", line 210, in main
        deps = CFG.main(**kwds)
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_f527b49a8476400baa043e4012aa9804\buildconfig\config_win.py", line 576, in main
        and download_win_prebuilt.ask(**download_kwargs):
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_f527b49a8476400baa043e4012aa9804\buildconfig\download_win_prebuilt.py", line 302, in ask
        reply = raw_input(
    EOFError: EOF when reading a line
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/71/4f/b3a521bb4db6ef696bcffca58b833aa2e84f7e7c142951d506d840ced57a/pygame-1.9.5.tar.gz#sha256=d15e7238015095a12c19379565a66285e989fdcb3807ec360b27338cd8bdaf05 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pygame-1.9.4.tar.gz (4.8 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ulyss\AppData\Local\Programs\Python\Python310\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_d1761c259ef846e3aec3e17c6263bebb\\setup.py'"'"'; __file__='"'"'C:\\Users\\ulyss\\AppData\\Local\\Temp\\pip-install-le3iu_7w\\pygame_d1761c259ef846e3aec3e17c6263bebb\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ulyss\AppData\Local\Temp\pip-pip-egg-info-t7bzjk7k'
         cwd: C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_d1761c259ef846e3aec3e17c6263bebb\
    Complete output (40 lines):


    WARNING, No "Setup" File Exists, Running "config.py"
    Using WINDOWS configuration...

    Path for SDL not found.
    Too bad that is a requirement! Hand-fix the "Setup"
    Path for FONT not found.
    Path for IMAGE not found.
    Path for MIXER not found.
    Path for PNG not found.
    Path for JPEG not found.
    Path for PORTMIDI not found.
    Path for COPYLIB_tiff not found.
    Path for COPYLIB_z not found.
    Path for COPYLIB_vorbis not found.
    Path for COPYLIB_ogg not found.

    If you get compiler errors during install, doublecheck
    the compiler flags in the "Setup" file.

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ulyss\AppData\Local\Temp\pip-install-le3iu_7w\pygame_d1761c259ef846e3aec3e17c6263bebb\setup.py", line 203, in <module>
        extensions = read_setup_file('Setup')
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\distutils\extension.py", line 172, in read_setup_file
        line = expand_makefile_vars(line, vars)
      File "C:\Users\ulyss\AppData\Local\Programs\Python\Python310\lib\sysconfig.py", line 775, in expand_makefile_vars
        s = s[0:beg] + vars.get(m.group(1)) + s[end:]
    TypeError: can only concatenate str (not "NoneType") to str

    Continuing With "setup.py"
    Error with the "Setup" file,
    perhaps make a clean copy from "Setup.in".
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/CompileWindows
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b2/6b/c510f0853765eb2219ca5aa3d416d65bb0dea7cd9bb2984aea0a0e04c24d/pygame-1.9.4.tar.gz#sha256=700d1781c999af25d11bfd1f3e158ebb660f72ebccb2040ecafe5069d0b2c0b6 (from https://pypi.org/simple/pygame/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  [...]
ERROR: Could not find a version that satisfies the requirement pygame (from versions: 1.9.2rc1, 1.9.2, 1.9.3, 1.9.4.dev0, 1.9.4rc1, 1.9.4, 1.9.5rc1, 1.9.5rc2, 1.9.5, 1.9.6rc1, 1.9.6rc2, 1.9.6, 2.0.0.dev1, 2.0.0.dev2, 2.0.0.dev3, 2.0.0.dev4, 2.0.0.dev6, 2.0.0.dev8, 2.0.0.dev10, 2.0.0.dev12, 2.0.0.dev14, 2.0.0.dev16, 2.0.0.dev18, 2.0.0.dev20, 2.0.0.dev22, 2.0.0.dev24, 2.0.0, 2.0.1.dev1, 2.0.1, 2.0.2.dev2)
ERROR: No matching distribution found for pygame
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\ulyss\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.
```

**Comment by TheBandik** [comment] 2021-10-09 10:47
I had the same problem and it worked

**Comment by ankith26** [comment] 2021-10-09 11:54
Nice, the 3.10 wheels works, and also we will be doing a dev release with those by this weekend! So I am closing this issue as the issue is already sorted, but feel free to reopen if some issues persist

**Closed by ankith26** 2021-10-09 11:54 UTC
