### ISSUE TITLE
Game crashing when shooting 

### ISSUE THREAD

**Issue by Jhon112** [pygame/pygame#1461] opened 2019-10-26 17:46 UTC
Hi there! So there seems to be a problem when running the example game, I'm actually new to pygame and just installed it, once I ran the script given on the getting started page the game started working, but as soon as I press the space bar the game crashes showing the following error: 

`⇒  python3 -m pygame.examples.aliens
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html

Fatal Python error: take_gil: NULL tstate
[1]    7971 abort (core dumped)  python3 -m pygame.examples.aliens
`
The window is not actually close but it gets stuck instead.

OS info:
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial

**Comment by robertpfeiffer** [comment] 2019-11-04 14:55
this might be a duplicate of #1092

**Comment by robertpfeiffer** [comment] 2019-11-04 14:59
I could not *quite* reproduce this, but I get

> ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred

when I run your example on Python 2.7 and pygame-2.0.0-dev6, but not with Python 3.6

**Closed** 2019-11-08 06:17 UTC
Labels: 1.9.6
