### ISSUE TITLE
screenshot of GL screen doesn't include alpha

### ISSUE THREAD

**Issue by illume** [pygame/pygame#1509] opened 2019-11-17 19:22 UTC
@imallett wrote:
> Trying to take a screenshot in OpenGL with alpha, and it's not working (i.e., glClearColor has alpha set to less than 1.0, but the result from glReadPixels is all 1.0s). You'd get this result if the framebuffer was created RGB instead of RGBA.

> I vaguely remember this working before, so has the window creation changed from RGBA to RGB? If so, is there a flag to pass to set it back to RGBA? (I already tried depth=32 . . .)?
Well, in-answer to the second question, you can fix this with just:

>pygame.display.gl_set_attribute(GL_ALPHA_SIZE,8)

> I don't recall this being necessary before, though.

**Related Docs:** https://www.pygame.org/docs/ref/display.html#pygame.display.set_mode

**To do to close**:

- [ ] Test if test case below behaves differently on any version of pygame (try 1.9.1, 1.9.6, 2.0.0.dev8)
- [ ] If it is different between pygame 1 & 2 we may need to note for migration guide if it is the same, we can close this issue.

**Comment by nthykier** [comment] 2020-04-27 21:39
@imallett Would it be possible to get a full runnable example to reproduce this bug?

Also, which version of pygame and SDL was this found in?

**Comment by imallett** [comment] 2020-04-27 22:51
As a point of order: I didn't myself report this as a bug because I'm not sure it actually *is* a bug. In particular, RGB is seen as "more basic" than RGBA, and generally if you want a feature in OpenGL you have to request it. So really, this is a question about what the default should be.

The usual blending function (`GL_SRC_ALPHA`, `GL_ONE_MINUS_SRC_ALPHA`) doesn't depend on the destination alpha, so either default will be fine for most users. You'll only get problems when you try to read from the framebuffer (which won't happen in modern OpenGL anyway; you read from FBOs, probably with PBOs, and you're explicit about all this). One might think to use RGBA always, just to be safe, but this has more memory/perf cost than RGB, and without transparent windows it might be a bit unintuitive. There's also the consistency argument: other platforms have RGB, not RGBA, as a default, AFAIK.

So, my opinion is overall that, if this is a regression (and it might not be), it's a *good* regression: RGB should be the default, for consistency and performance. However, I am not terribly averse to an RGBA default. Perhaps one should make it a required argument, so there are no defaults at all? There are different ways one can resolve this.

Anyway, enough commentary. The current behavior is easy to demonstrate:
```python
import os, sys
with open(os.devnull, "w") as f:
    oldstdout=sys.stdout; sys.stdout=f; import pygame; sys.stdout=oldstdout
from pygame.locals import *
from OpenGL.GL import *

print(sys.version.split(" ")[0])
print(pygame.ver)
pygame.display.init()
pygame.display.gl_set_attribute(GL_ALPHA_SIZE,8) #enable or disable this line
pygame.display.set_mode((1,1),OPENGL)

glClearColor( 1.0,0.0,1.0, 0.5 )
glClear(GL_COLOR_BUFFER_BIT)
print(glReadPixels(0,0,1,1,GL_RGBA,GL_FLOAT)[0][0][3])

pygame.quit()
```
This basically just clears the screen to `0.5` alpha and then reads what we actually got. The Python and pygame versions are also printed. On one of my computers (Win 10 x86-64, NVIDIA GTX 1080), as written, it produces:
```
3.7.3
1.9.6
0.49803925
```
(Note: the result is slightly less than `0.5` on account of the framebuffer backing being bytes, not `float`s.) When you comment the marked line, however, you'll instead get `1.0`.

**Comment by nthykier** [comment] 2020-04-28 21:30
Thanks for the clarification.  In light of your follow up message, I am inclined to say this issue is about documenting the change in the release notes (or an Pygame 1 -> Pygame 2 migration guide) more than it is a code change.

**Comment by imallett** [comment] 2020-04-28 21:39
Sounds good. Note that as I said I'm not sure this is a change. The behavior should be documented, but one should check previous versions to see if this is a change or merely a clarification.

**Comment by MyreMylar** [comment] 2020-10-27 12:12
From my testing so far, on windows, the behaviour of the test program is the same in pygame versions 1.9.6 and 2.0.0. 

Debating whether to install python 2.7 again to test pygame 1.9.1.

**Comment by MyreMylar** [comment] 2020-10-27 12:30
OK for pygame 1.9.1 I had to change the output format of the print like so:

```
import os, sys
with open(os.devnull, "w") as f:
    oldstdout=sys.stdout; sys.stdout=f; import pygame; sys.stdout=oldstdout
from pygame.locals import *
from OpenGL.GL import *

print(sys.version.split(" ")[0])
print(pygame.ver)
pygame.display.init()
#pygame.display.gl_set_attribute(GL_ALPHA_SIZE,8) #enable or disable this line
pygame.display.set_mode((1,1),OPENGL)

glClearColor( 1.0,0.0,1.0, 0.5 )
glClear(GL_COLOR_BUFFER_BIT)
print("0x%x" % glReadPixels(0, 0, 1, 1, GL_RGBA, GL_UNSIGNED_INT_8_8_8_8)[0][0])

pygame.quit()
```

But the result is the same 1 (or FF) alpha without `pygame.display.gl_set_attribute(GL_ALPHA_SIZE,8)` and roughly 0.5 (or 7f) alpha with it.

The behaviour seems to be the same on all pygame versions. I think it is safe to close this.

**Closed** 2020-10-27 12:31 UTC
Labels: 2.0, Difficulty: Easy, display, docs, needs-investigation, opengl
