### ISSUE TITLE
Pygame 2.0.0.dev6 ignores depth when creating display

### ISSUE THREAD

**Issue by ks0ze** [pygame/pygame#1560] opened 2020-01-16 22:44 UTC
On Windows 10 with Pygame 2.0.0.dev6 I'm trying to create a display with depth=16 but the resulting surface has depth=32.

This example code shows the difference:

> import pygame
> pygame.init()
> DISPLAY = pygame.display.set_mode(size=(256, 64), depth=16)
> print(DISPLAY)
> SURFACE = pygame.Surface(size=(256, 64), depth=16)
> print(SURFACE)

In Pygame 1.9.6 the above code prints:

> <Surface(256x64x16 SW)>
> <Surface(256x64x16 SW)>

but in Pygame 2.0.0.dev6 it creates a 32bit DISPLAY:

> <Surface(256x64x32 SW)>
> <Surface(256x64x16 SW)>

**Comment by illume** [comment] 2020-01-19 09:04
Thanks for the report.

This is a duplicate of https://github.com/pygame/pygame/issues/991

**Closed by illume** 2020-01-19 09:04 UTC
