### ISSUE TITLE
system fonts in PyGame

### ISSUE THREAD

**Issue by bruceblosser** [pygame/pygame#2872] opened 2021-11-28 04:30 UTC
On a Windows 10 machine, using PyCharm 2021.2.2 (Community Edition)

when I use "font = pygame.font.Font('FREESCPT.TTF', 32)"   in a pygame program, it lets me use the full filename. But I have put a copy of the file, where ever I saved my python program.

So I thought i would use SysFont instead, like this:  "font = pygame.font.SysFont('Times New Roman', 32)   it does work, but if I try to use the Italic, bold, or other versions of the font, I can't seem to get that to work!

Any thoughts on getting this to work?

**Comment by Starbuck5** [comment] 2021-11-28 09:16
> if I try to use the Italic, bold, or other versions of the font, I can't seem to get that to work!

How are you trying to do this?

Presumably you're using the SysFont italics and bold parameters?

**Comment by MyreMylar** [comment] 2021-11-28 09:34
> > if I try to use the Italic, bold, or other versions of the font, I can't seem to get that to work!
> 
> How are you trying to do this?
> 
> Presumably you're using the SysFont italics and bold parameters?

I just tried using these and get a bold version of times new roman.

```
font = pygame.font.SysFont('Times New Roman', size=12, bold=True)
```

**Comment by ankith26** [comment] 2021-11-28 09:42
Can't reproduce this issue either, I'm doing something like
```py
font = pygame.font.SysFont('Times New Roman', 32)
win.blit(font.render("Testing font", True, (255, 255, 255)), (0, 0))
font.bold = True
win.blit(font.render("Testing font", True, (255, 255, 255)), (0, 40))
font.bold = False
font.italic = True
win.blit(font.render("Testing font", True, (255, 255, 255)), (0, 80))
```
and I get the expected output

**Comment by bruceblosser** [comment] 2021-11-29 09:43
obviously this issue is more complicated than I thought!  Going to test the following code, as suggested!
font = pygame.font.SysFont('Times New Roman', size=12, bold=True)

**Comment by ankith26** [comment] 2021-12-01 08:40
Any update on this issue?

I'm inclined to close this issue because it's not reproducible on other windows platforms, but please feel free to reopen if you've got some sample code that shows this issue, and you are sure that the bug caused is due to pygame and not your code ;)

**Closed by ankith26** 2021-12-01 08:40 UTC
